#!/usr/bin/env python3
"""
extract_intro_scene.py -- Convert pokerred intro cutscene assets to GB 2bpp C arrays.

Generates:
  src/data/intro_scene_data.h
  src/data/intro_scene_data.c

Sources (pokered-master/gfx/intro):
  - gengar.png           (168x56, 21x7 tiles: three 7x7 frames side-by-side)
  - gengar_1.tilemap     (49 bytes)
  - gengar_2.tilemap     (49 bytes)
  - gengar_3.tilemap     (49 bytes)
  - red_nidorino_1.png   (48x48, 6x6 tiles)
  - red_nidorino_2.png   (48x48, 6x6 tiles)
  - red_nidorino_3.png   (48x48, 6x6 tiles)
"""

from pathlib import Path

from extract_title_screen import (
    decode_png_grayscale,
    pixels_to_gb2bpp,
    tile_bytes_to_c_lines,
)

POKERED = Path(r"C:\Users\Anthony\pokered\pokered-master")
OUT = Path(r"C:\Users\Anthony\pokered\src\data")
INTRO = POKERED / "gfx" / "intro"

GENGAR_PNG = INTRO / "gengar.png"
GENGAR_TM1 = INTRO / "gengar_1.tilemap"
GENGAR_TM2 = INTRO / "gengar_2.tilemap"
GENGAR_TM3 = INTRO / "gengar_3.tilemap"
NIDO1_PNG = INTRO / "red_nidorino_1.png"
NIDO2_PNG = INTRO / "red_nidorino_2.png"
NIDO3_PNG = INTRO / "red_nidorino_3.png"


def _tiles_from_blob(blob):
    return [blob[i * 16 : (i + 1) * 16] for i in range(len(blob) // 16)]


def _reorder_tiles_columns(blob, tiles_w, tiles_h):
    """Reorder tile stream from row-major to RGBDS --columns order."""
    row_major = _tiles_from_blob(blob)
    out = []
    for tx in range(tiles_w):
        for ty in range(tiles_h):
            out.append(row_major[ty * tiles_w + tx])
    return b"".join(out)


def _frame_tiles_from_gengar(blob, frame_idx):
    """Return 49 tiles (7x7) for frame_idx in [0,1,2] from 21x7 tile strip."""
    all_tiles = _tiles_from_blob(blob)
    out = []
    for ty in range(7):
        for tx in range(7):
            src_tx = frame_idx * 7 + tx
            out.append(all_tiles[ty * 21 + src_tx])
    return out


def main():
    gw, gh, gp, gbd = decode_png_grayscale(GENGAR_PNG)
    n1w, n1h, n1p, n1bd = decode_png_grayscale(NIDO1_PNG)
    n2w, n2h, n2p, n2bd = decode_png_grayscale(NIDO2_PNG)
    n3w, n3h, n3p, n3bd = decode_png_grayscale(NIDO3_PNG)

    assert (gw, gh) == (168, 56)
    assert (n1w, n1h) == (48, 48)
    assert (n2w, n2h) == (48, 48)
    assert (n3w, n3h) == (48, 48)

    gengar_blob = pixels_to_gb2bpp(gw, gh, gp, gbd, invert=True)
    nido1_blob = pixels_to_gb2bpp(n1w, n1h, n1p, n1bd, invert=True)
    nido2_blob = pixels_to_gb2bpp(n2w, n2h, n2p, n2bd, invert=True)
    nido3_blob = pixels_to_gb2bpp(n3w, n3h, n3p, n3bd, invert=True)

    frame_tiles = [
        _frame_tiles_from_gengar(gengar_blob, 0),
        _frame_tiles_from_gengar(gengar_blob, 1),
        _frame_tiles_from_gengar(gengar_blob, 2),
    ]

    tm1 = GENGAR_TM1.read_bytes()
    tm2 = GENGAR_TM2.read_bytes()
    tm3 = GENGAR_TM3.read_bytes()
    assert len(tm1) == 49 and len(tm2) == 49 and len(tm3) == 49

    # Reconstruct FightIntroBackMon tile bank as used by the tilemaps:
    # tile 0 is blank (in the map), and non-zero IDs map to this 94-tile bank.
    back_tiles = [None] * 95
    back_tiles[0] = bytes([0] * 16)
    for f_idx, tm in enumerate((tm1, tm2, tm3)):
        for p, tile_id in enumerate(tm):
            if tile_id == 0:
                continue
            tile = frame_tiles[f_idx][p]
            if back_tiles[tile_id] is None:
                back_tiles[tile_id] = tile
            else:
                assert back_tiles[tile_id] == tile

    for i in range(1, 95):
        assert back_tiles[i] is not None, f"Missing reconstructed gengar tile {i}"
    back_blob = b"".join(back_tiles[1:95])

    back_tiles_count = len(back_blob) // 16
    nido_tiles_count = (len(nido1_blob) + len(nido2_blob) + len(nido3_blob)) // 16
    assert back_tiles_count == 94
    assert nido_tiles_count == 108

    # Makefile builds intro front mons with `RGBGFXFLAGS += --columns`.
    nido1_blob = _reorder_tiles_columns(nido1_blob, 6, 6)
    nido2_blob = _reorder_tiles_columns(nido2_blob, 6, 6)
    nido3_blob = _reorder_tiles_columns(nido3_blob, 6, 6)
    nido_blob = nido1_blob + nido2_blob + nido3_blob

    h_lines = [
        "#pragma once",
        "/* intro_scene_data.h -- AUTO-GENERATED by tools/extract_intro_scene.py. */",
        "#include <stdint.h>",
        "",
        "#define INTRO_GENGAR_BACK_TILES     94",
        "#define INTRO_NIDORINO_FRONT_TILES 108",
        "#define INTRO_GENGAR_TILEMAP_TILES  49",
        "",
        "extern const uint8_t gIntroGengarBackTiles[INTRO_GENGAR_BACK_TILES][16];",
        "extern const uint8_t gIntroNidorinoFrontTiles[INTRO_NIDORINO_FRONT_TILES][16];",
        "extern const uint8_t gIntroGengarTilemap1[INTRO_GENGAR_TILEMAP_TILES];",
        "extern const uint8_t gIntroGengarTilemap2[INTRO_GENGAR_TILEMAP_TILES];",
        "extern const uint8_t gIntroGengarTilemap3[INTRO_GENGAR_TILEMAP_TILES];",
        "",
    ]

    c_lines = [
        "/* intro_scene_data.c -- AUTO-GENERATED by tools/extract_intro_scene.py. */",
        "#include \"intro_scene_data.h\"",
        "",
        "const uint8_t gIntroGengarBackTiles[INTRO_GENGAR_BACK_TILES][16] = {",
        *tile_bytes_to_c_lines(back_blob),
        "};",
        "",
        "const uint8_t gIntroNidorinoFrontTiles[INTRO_NIDORINO_FRONT_TILES][16] = {",
        *tile_bytes_to_c_lines(nido_blob),
        "};",
        "",
        "const uint8_t gIntroGengarTilemap1[INTRO_GENGAR_TILEMAP_TILES] = {",
        "    " + ", ".join(f"0x{b:02X}" for b in tm1),
        "};",
        "",
        "const uint8_t gIntroGengarTilemap2[INTRO_GENGAR_TILEMAP_TILES] = {",
        "    " + ", ".join(f"0x{b:02X}" for b in tm2),
        "};",
        "",
        "const uint8_t gIntroGengarTilemap3[INTRO_GENGAR_TILEMAP_TILES] = {",
        "    " + ", ".join(f"0x{b:02X}" for b in tm3),
        "};",
        "",
    ]

    (OUT / "intro_scene_data.h").write_text("\n".join(h_lines), encoding="ascii")
    (OUT / "intro_scene_data.c").write_text("\n".join(c_lines), encoding="ascii")

    print(
        "Wrote intro_scene_data.[ch]: "
        f"gengar_back={back_tiles_count}, nidorino_front={nido_tiles_count}, tilemap=49x3"
    )


if __name__ == "__main__":
    main()
