#!/usr/bin/env python3
"""Generate src/data/pokemon_names_gen.h from pokered-master/data/pokemon/names.asm.

MonsterNames is in INTERNAL species order (entry 0 = Rhydon = internal ID 0x01).
We cross-reference with gSpeciesToDex[] (from src/data/base_stats.c) to output
kPokemonNames[152] indexed by Pokédex number (1-151; [0] is empty).

Usage:  python tools/extract_pokemon.py
        (run from repo root; writes src/data/pokemon_names_gen.h)
"""
import re, sys, os

REPO_ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAMES_ASM  = os.path.join(REPO_ROOT, "pokered-master", "data", "pokemon", "names.asm")
STATS_C    = os.path.join(REPO_ROOT, "src", "data", "base_stats.c")
OUT_H      = os.path.join(REPO_ROOT, "src", "data", "pokemon_names_gen.h")


def parse_names(path):
    """Return list of 151 ASCII names in internal species order.
    Entry 0 = Rhydon (internal ID 0x01), entry 1 = Kangaskhan (0x02), …
    Special chars: ♂ → .M, ♀ → .F (ASCII-safe for C string literals).
    """
    names = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = re.match(r'\s*dname\s+"([^"]+)"', line)
            if m:
                raw = m.group(1)
                raw = raw.replace("\u2642", ".M").replace("\u2640", ".F")
                names.append(raw)
    return names


def parse_species_to_dex(path):
    """Extract gSpeciesToDex[256] values from base_stats.c."""
    with open(path, encoding="utf-8") as f:
        content = f.read()
    m = re.search(r'gSpeciesToDex\[256\]\s*=\s*\{([^}]+)\}', content, re.DOTALL)
    if not m:
        raise ValueError("gSpeciesToDex[256] not found in " + path)
    body = m.group(1)
    # Strip block comments (/* 0x00 */ labels) before extracting numbers
    body = re.sub(r'/\*[^*]*\*/', '', body)
    values = re.findall(r'\b\d+\b', body)
    if len(values) != 256:
        raise ValueError(f"Expected 256 values, got {len(values)}")
    return [int(v) for v in values]


def main():
    internal_names = parse_names(NAMES_ASM)
    # names.asm has 190 entries: internal IDs 0x01-0xBD, including MISSINGNO. slots
    if len(internal_names) < 151:
        print(f"ERROR: expected >=151 names, got {len(internal_names)}", file=sys.stderr)
        sys.exit(1)

    species_to_dex = parse_species_to_dex(STATS_C)

    # Build dex→name: scan internal IDs 1..255, look up which dex each maps to.
    dex_to_name = [""] * 152          # [0] unused
    for internal_id in range(1, 256):
        dex = species_to_dex[internal_id]
        if 1 <= dex <= 151:
            dex_to_name[dex] = internal_names[internal_id - 1]

    missing = [d for d in range(1, 152) if not dex_to_name[d]]
    if missing:
        print(f"WARNING: no name for dex {missing}", file=sys.stderr)

    lines = [
        "/* pokemon_names_gen.h — Generated by tools/extract_pokemon.py",
        " * DO NOT EDIT — run tools/extract_pokemon.py to regenerate.",
        " *",
        " * kPokemonNames[dex] = ASCII name string, indices 1-151.",
        " * kPokemonNames[0]   = \"\" (unused slot).",
        " */",
        "#pragma once",
        "",
        "#define NUM_POKEMON_NAMES 152",
        "",
        "static const char * const kPokemonNames[NUM_POKEMON_NAMES] = {",
        '    [0] = "",  /* unused */',
    ]
    for dex in range(1, 152):
        lines.append(f'    [{dex:3d}] = "{dex_to_name[dex]}",')
    lines += ["};", ""]

    output = "\n".join(lines)
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"Wrote {OUT_H}", file=sys.stderr)
    filled = sum(1 for n in dex_to_name[1:] if n)
    print(f"  {filled}/151 entries filled", file=sys.stderr)


if __name__ == "__main__":
    main()
