#!/usr/bin/env python3
"""
extract_move_sfx.py -- Convert pokered move SFX table ASM to C data arrays.

Source:
  - pokered-master/data/moves/sfx.asm (MoveSoundTable)

Outputs:
  - src/data/move_sfx_data.h
  - src/data/move_sfx_data.c
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(r"C:\Users\Anthony\pokered")
SRC_ASM = ROOT / "pokered-master" / "data" / "moves" / "sfx.asm"
OUT_DIR = ROOT / "src" / "data"
OUT_H = OUT_DIR / "move_sfx_data.h"
OUT_C = OUT_DIR / "move_sfx_data.c"

DB_RE = re.compile(
    r"^\s*db\s+([A-Z0-9_]+)\s*,\s*\$([0-9a-fA-F]{2})\s*,\s*\$([0-9a-fA-F]{2})\s*(?:;\s*(.*))?$"
)


def parse_rows(text: str):
    rows = []
    for raw in text.splitlines():
        line = raw
        m = DB_RE.match(line)
        if not m:
            continue
        sfx_symbol = m.group(1)
        pitch_mod = int(m.group(2), 16)
        tempo_mod = int(m.group(3), 16)
        comment = (m.group(4) or "").strip()
        rows.append((sfx_symbol, pitch_mod, tempo_mod, comment))
    return rows


def emit_header(row_count: int) -> str:
    return "\n".join(
        [
            "#pragma once",
            "/* move_sfx_data.h -- AUTO-GENERATED by tools/extract_move_sfx.py. */",
            "#include <stdint.h>",
            "",
            "typedef struct {",
            "    const char *sfx_symbol; /* ASM token, e.g. SFX_BATTLE_0B */",
            "    uint8_t pitch_mod;",
            "    uint8_t tempo_mod;",
            "} move_sfx_data_t;",
            "",
            f"#define MOVE_SFX_DATA_COUNT {row_count}",
            "",
            "extern const move_sfx_data_t gMoveSfxData[MOVE_SFX_DATA_COUNT];",
            "",
        ]
    )


def emit_source(rows) -> str:
    lines = [
        "/* move_sfx_data.c -- AUTO-GENERATED by tools/extract_move_sfx.py. */",
        '#include "move_sfx_data.h"',
        "",
        "const move_sfx_data_t gMoveSfxData[MOVE_SFX_DATA_COUNT] = {",
    ]
    for i, (sfx_symbol, pitch_mod, tempo_mod, comment) in enumerate(rows):
        suffix = f" /* {i:03d}: {comment} */" if comment else f" /* {i:03d} */"
        lines.append(
            f'    {{ "{sfx_symbol}", 0x{pitch_mod:02X}, 0x{tempo_mod:02X} }},{suffix}'
        )
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> None:
    text = SRC_ASM.read_text(encoding="utf-8")
    rows = parse_rows(text)
    if not rows:
        raise RuntimeError(f"No move SFX rows parsed from {SRC_ASM}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(emit_header(len(rows)), encoding="ascii")
    OUT_C.write_text(emit_source(rows), encoding="ascii")
    print(f"Wrote {OUT_H} and {OUT_C} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
