#!/usr/bin/env python3
"""Generate src/data/item_data_gen.h from pokered-master item data.

Usage:  python tools/extract_items.py > src/data/item_data_gen.h
"""
import re, sys, os

# ---- Pokéred charmap (longest sequences first) -------------------------
MULTI = {"'d": 0xBB, "'l": 0xBC, "'s": 0xBD, "'t": 0xBE, "'v": 0xBF,
         "'r": 0xE4, "'m": 0xE5}

SINGLE = {
    **{chr(ord('A') + i): 0x80 + i for i in range(26)},
    **{chr(ord('a') + i): 0xA0 + i for i in range(26)},
    'é': 0xBA,
    ' ': 0x7F, '.': 0xE8, '-': 0xE3, '?': 0xE6, '!': 0xE7,
    ',': 0xF4, '/': 0xF3, ':': 0x9C, ';': 0x9D,
    '(': 0x9A, ')': 0x9B, '[': 0x9E, ']': 0x9F,
    "'": 0x71,                          # closing single quote / apostrophe
    '\u2019': 0x71,                     # curly right apostrophe
    '\u2018': 0x70,                     # curly left apostrophe
    **{str(d): 0xF6 + d for d in range(10)},
    '×': 0xF1, '¥': 0xF0,
}

CHAR_TERM = 0x50
ITEM_NAME_LENGTH = 13   # 12 display chars + terminator

def encode(s):
    result = []
    i = 0
    while i < len(s):
        matched = False
        for seq, code in MULTI.items():
            if s[i:i+len(seq)] == seq:
                result.append(code)
                i += len(seq)
                matched = True
                break
        if not matched:
            c = s[i]
            if c in SINGLE:
                result.append(SINGLE[c])
            else:
                print(f"# WARNING: unknown char {repr(c)} in {repr(s)}", file=sys.stderr)
                result.append(0x7F)
            i += 1
    result = result[:ITEM_NAME_LENGTH - 1]
    result += [CHAR_TERM] * (ITEM_NAME_LENGTH - len(result))
    return result

ROOT = os.path.join(os.path.dirname(__file__), "..")
names_path     = os.path.join(ROOT, "pokered-master/data/items/names.asm")
keyitems_path  = os.path.join(ROOT, "pokered-master/data/items/key_items.asm")

names = []
with open(names_path, encoding='utf-8') as f:
    for line in f:
        m = re.search(r'li\s+"([^"]*)"', line)
        if m:
            names.append(m.group(1))

key_flags = []
with open(keyitems_path, encoding='utf-8') as f:
    for line in f:
        m = re.search(r'dbit\s+(TRUE|FALSE)', line)
        if m:
            key_flags.append(1 if m.group(1) == 'TRUE' else 0)

NUM_ITEMS = 85  # regular items only (IDs 1-85, $01-$53)

print("/* item_data_gen.h — generated by tools/extract_items.py */")
print("/* DO NOT EDIT — regenerate with: python tools/extract_items.py > src/data/item_data_gen.h */")
print("#pragma once")
print("#include <stdint.h>")
print()
print(f"#define NUM_ITEMS  {NUM_ITEMS}  /* regular items, IDs 1..NUM_ITEMS */")
print()

print("/* Pokéred-encoded item names, ITEM_NAME_LENGTH bytes each.")
print(" * Index 0 = NO_ITEM (empty). Index N = item_id N. */")
print(f"static const uint8_t kItemNames[][{ITEM_NAME_LENGTH}] = {{")
# [0] NO_ITEM
print(f"    /* [ 0] NO_ITEM       */ {{ {', '.join(f'0x{CHAR_TERM:02X}' for _ in range(ITEM_NAME_LENGTH))} }},")
for i, name in enumerate(names):
    encoded = encode(name)
    hex_bytes = ', '.join(f'0x{b:02X}' for b in encoded)
    print(f"    /* [{i+1:2d}] {name[:13]:<13s} */ {{ {hex_bytes} }},")
print("};")
print()

# Key item flags as a packed byte array (bit i set → item (i+1) is a key item)
print("/* Key item flags, one bit per item. Bit (id-1) set = key item (cannot toss). */")
num_bytes = (NUM_ITEMS + 7) // 8
packed = [0] * num_bytes
for i, flag in enumerate(key_flags[:NUM_ITEMS]):
    if flag:
        packed[i // 8] |= (1 << (i % 8))
hex_packed = ', '.join(f'0x{b:02X}' for b in packed)
print(f"static const uint8_t kKeyItemFlags[{num_bytes}] = {{ {hex_packed} }};")
