#!/usr/bin/env python3
"""
extract_move_anim_tiles.py -- Convert pokered move animation tilesets to C arrays.

Sources (pokered-master/gfx/battle):
  - move_anim_0.png  (used by MoveAnimationTiles0 and MoveAnimationTiles2)
  - move_anim_1.png  (used by MoveAnimationTiles1)

Outputs:
  - src/data/move_anim_tiles.h
  - src/data/move_anim_tiles.c
"""

from pathlib import Path
import struct
import zlib

POKERED = Path(r"C:\Users\Anthony\pokered\pokered-master")
OUT = Path(r"C:\Users\Anthony\pokered\src\data")
BATTLE = POKERED / "gfx" / "battle"

MOVE_ANIM_0_PNG = BATTLE / "move_anim_0.png"
MOVE_ANIM_1_PNG = BATTLE / "move_anim_1.png"

# From engine/battle/animations.asm MoveAnimationTilesPointers.
MOVE_ANIM_TILESET0_COUNT = 79
MOVE_ANIM_TILESET1_COUNT = 79
MOVE_ANIM_TILESET2_COUNT = 64  # shares data with tileset0


def decode_png_grayscale(path: Path):
    data = path.read_bytes()
    assert data[:8] == b"\x89PNG\r\n\x1a\n", f"Not PNG: {path}"

    i = 8
    width = height = bit_depth = color_type = 0
    idat = []
    while i < len(data):
        length = struct.unpack(">I", data[i : i + 4])[0]
        ctype = data[i + 4 : i + 8]
        cdata = data[i + 8 : i + 8 + length]
        if ctype == b"IHDR":
            width, height = struct.unpack(">II", cdata[:8])
            bit_depth = cdata[8]
            color_type = cdata[9]
            assert color_type == 0, f"Expected grayscale PNG: {path}"
            assert bit_depth == 2, f"Expected 2bpp PNG: {path}"
        elif ctype == b"IDAT":
            idat.append(cdata)
        i += 12 + length

    raw = zlib.decompress(b"".join(idat))
    stride = (width * bit_depth + 7) // 8
    pixels = []
    prev = bytes(stride)
    pos = 0
    for _ in range(height):
        filt = raw[pos]
        pos += 1
        row = bytearray(raw[pos : pos + stride])
        pos += stride

        if filt == 1:
            for j in range(1, stride):
                row[j] = (row[j] + row[j - 1]) & 0xFF
        elif filt == 2:
            for j in range(stride):
                row[j] = (row[j] + prev[j]) & 0xFF
        elif filt == 3:
            for j in range(stride):
                a = row[j - 1] if j > 0 else 0
                b = prev[j]
                row[j] = (row[j] + ((a + b) // 2)) & 0xFF
        elif filt == 4:
            for j in range(stride):
                a = row[j - 1] if j > 0 else 0
                b = prev[j]
                c = prev[j - 1] if j > 0 else 0
                pa = abs(b - c)
                pb = abs(a - c)
                pc = abs(a + b - 2 * c)
                pr = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                row[j] = (row[j] + pr) & 0xFF
        elif filt != 0:
            raise ValueError(f"Unsupported PNG filter {filt} in {path}")

        prev = bytes(row)
        for b in row:
            for shift in (6, 4, 2, 0):
                pixels.append((b >> shift) & 0x3)

    return width, height, pixels[: width * height]


def pixels_to_gb2bpp(width: int, height: int, pixels):
    assert width % 8 == 0 and height % 8 == 0
    out = bytearray()
    tiles_x = width // 8
    tiles_y = height // 8

    for ty in range(tiles_y):
        for tx in range(tiles_x):
            for row in range(8):
                lo = 0
                hi = 0
                for col in range(8):
                    pv = pixels[(ty * 8 + row) * width + (tx * 8 + col)]
                    gb = 3 - pv  # grayscale PNG -> GB palette index
                    bit = 7 - col
                    if gb & 1:
                        lo |= 1 << bit
                    if gb & 2:
                        hi |= 1 << bit
                out.append(lo)
                out.append(hi)

    return bytes(out)


def emit_tiles(blob: bytes):
    assert len(blob) % 16 == 0
    lines = []
    for i in range(len(blob) // 16):
        t = blob[i * 16 : (i + 1) * 16]
        lines.append("    { " + ", ".join(f"0x{b:02X}" for b in t) + " },")
    return lines


def main():
    w0, h0, p0 = decode_png_grayscale(MOVE_ANIM_0_PNG)
    w1, h1, p1 = decode_png_grayscale(MOVE_ANIM_1_PNG)
    assert (w0, h0) == (128, 40), f"Unexpected move_anim_0 size {(w0, h0)}"
    assert (w1, h1) == (128, 40), f"Unexpected move_anim_1 size {(w1, h1)}"

    t0 = pixels_to_gb2bpp(w0, h0, p0)
    t1 = pixels_to_gb2bpp(w1, h1, p1)
    tiles0 = len(t0) // 16
    tiles1 = len(t1) // 16
    assert tiles0 >= MOVE_ANIM_TILESET0_COUNT
    assert tiles1 >= MOVE_ANIM_TILESET1_COUNT

    t0 = t0[: MOVE_ANIM_TILESET0_COUNT * 16]
    t1 = t1[: MOVE_ANIM_TILESET1_COUNT * 16]

    h = [
        "#pragma once",
        "/* move_anim_tiles.h -- AUTO-GENERATED by tools/extract_move_anim_tiles.py. */",
        "#include <stdint.h>",
        "",
        f"#define MOVE_ANIM_TILESET0_TILES {MOVE_ANIM_TILESET0_COUNT}",
        f"#define MOVE_ANIM_TILESET1_TILES {MOVE_ANIM_TILESET1_COUNT}",
        f"#define MOVE_ANIM_TILESET2_TILES {MOVE_ANIM_TILESET2_COUNT}",
        "",
        "extern const uint8_t gMoveAnimTileset0[MOVE_ANIM_TILESET0_TILES][16];",
        "extern const uint8_t gMoveAnimTileset1[MOVE_ANIM_TILESET1_TILES][16];",
        "",
    ]

    c = [
        "/* move_anim_tiles.c -- AUTO-GENERATED by tools/extract_move_anim_tiles.py. */",
        "#include \"move_anim_tiles.h\"",
        "",
        "const uint8_t gMoveAnimTileset0[MOVE_ANIM_TILESET0_TILES][16] = {",
        *emit_tiles(t0),
        "};",
        "",
        "const uint8_t gMoveAnimTileset1[MOVE_ANIM_TILESET1_TILES][16] = {",
        *emit_tiles(t1),
        "};",
        "",
    ]

    (OUT / "move_anim_tiles.h").write_text("\n".join(h), encoding="ascii")
    (OUT / "move_anim_tiles.c").write_text("\n".join(c), encoding="ascii")

    print(
        "Wrote move_anim_tiles.[ch] "
        f"(tileset0={MOVE_ANIM_TILESET0_COUNT}, tileset1={MOVE_ANIM_TILESET1_COUNT}, "
        f"tileset2={MOVE_ANIM_TILESET2_COUNT} from tileset0)"
    )


if __name__ == "__main__":
    main()

