#!/usr/bin/env python3
"""
extract_splash_screen.py -- Convert pokered splash assets to GB 2bpp C arrays.

Generates:
  src/data/splash_screen_data.h
  src/data/splash_screen_data.c

Sources (pokered-master/gfx/splash):
  - gamefreak_logo.png      (16x24, 2bpp, 2x3 tiles = 6)
  - falling_star.png        (8x8,   2bpp, 1 tile)
  - battle/move_anim_1.png  (128x40, 2bpp, tiles 3 and 19 used for big star)
  - gamefreak_presents.png  (104x8, 2bpp, 13 tiles; exported for reuse)
  - copyright.png           (152x8, 2bpp, 19 tiles)
  - title/gamefreak_inc.png (72x8,  2bpp, 9 tiles)
"""

from pathlib import Path

from extract_title_screen import (
    decode_png_grayscale,
    pixels_to_gb2bpp,
    tile_bytes_to_c_lines,
)

POKERED = Path(r"C:\Users\Anthony\pokered\pokered-master")
OUT = Path(r"C:\Users\Anthony\pokered\src\data")
SPLASH = POKERED / "gfx" / "splash"
TITLE = POKERED / "gfx" / "title"
BATTLE = POKERED / "gfx" / "battle"

GAMEFREAK_LOGO_PNG = SPLASH / "gamefreak_logo.png"
FALLING_STAR_PNG = SPLASH / "falling_star.png"
GAMEFREAK_PRESENTS_PNG = SPLASH / "gamefreak_presents.png"
MOVE_ANIM_1_PNG = BATTLE / "move_anim_1.png"
COPYRIGHT_PNG = SPLASH / "copyright.png"
GAMEFREAK_INC_PNG = TITLE / "gamefreak_inc.png"


def main():
    lw, lh, lp, lbd = decode_png_grayscale(GAMEFREAK_LOGO_PNG)
    sw, sh, sp, sbd = decode_png_grayscale(FALLING_STAR_PNG)
    pw, ph, pp, pbd = decode_png_grayscale(GAMEFREAK_PRESENTS_PNG)
    mw, mh, mp, mbd = decode_png_grayscale(MOVE_ANIM_1_PNG)
    cw, ch, cp, cbd = decode_png_grayscale(COPYRIGHT_PNG)
    iw, ih, ip, ibd = decode_png_grayscale(GAMEFREAK_INC_PNG)

    assert (lw, lh) == (16, 24)
    assert (sw, sh) == (8, 8)
    assert (pw, ph) == (104, 8)
    assert (mw, mh) == (128, 40)
    assert (cw, ch) == (152, 8)
    assert (iw, ih) == (72, 8)

    logo = pixels_to_gb2bpp(lw, lh, lp, lbd, invert=True)
    star = pixels_to_gb2bpp(sw, sh, sp, sbd, invert=True)
    move_anim_1 = pixels_to_gb2bpp(mw, mh, mp, mbd, invert=True)
    big_star = move_anim_1[3 * 16:4 * 16] + move_anim_1[19 * 16:20 * 16]
    presents = pixels_to_gb2bpp(pw, ph, pp, pbd, invert=True)
    copyright_tiles = pixels_to_gb2bpp(cw, ch, cp, cbd, invert=True)
    gamefreak_inc = pixels_to_gb2bpp(iw, ih, ip, ibd, invert=True)
    legal = copyright_tiles + gamefreak_inc

    logo_tiles = len(logo) // 16
    star_tiles = len(star) // 16
    big_star_tiles = len(big_star) // 16
    presents_tiles = len(presents) // 16
    legal_tiles = len(legal) // 16

    assert logo_tiles == 6
    assert star_tiles == 1
    assert big_star_tiles == 2
    assert presents_tiles == 13
    assert legal_tiles == 28

    h_lines = [
        "#pragma once",
        "/* splash_screen_data.h -- AUTO-GENERATED by tools/extract_splash_screen.py. */",
        "#include <stdint.h>",
        "",
        "#define SPLASH_GAMEFREAK_LOGO_TILES      6",
        "#define SPLASH_FALLING_STAR_TILES        1",
        "#define SPLASH_SHOOTING_STAR_TILES       2",
        "#define SPLASH_GAMEFREAK_PRESENTS_TILES 13",
        "#define SPLASH_LEGAL_TILES              28",
        "",
        "extern const uint8_t gSplashGameFreakLogoTiles[SPLASH_GAMEFREAK_LOGO_TILES][16];",
        "extern const uint8_t gSplashFallingStarTiles[SPLASH_FALLING_STAR_TILES][16];",
        "extern const uint8_t gSplashShootingStarTiles[SPLASH_SHOOTING_STAR_TILES][16];",
        "extern const uint8_t gSplashGameFreakPresentsTiles[SPLASH_GAMEFREAK_PRESENTS_TILES][16];",
        "extern const uint8_t gSplashLegalTiles[SPLASH_LEGAL_TILES][16];",
        "",
    ]

    c_lines = [
        "/* splash_screen_data.c -- AUTO-GENERATED by tools/extract_splash_screen.py. */",
        "#include \"splash_screen_data.h\"",
        "",
        "const uint8_t gSplashGameFreakLogoTiles[SPLASH_GAMEFREAK_LOGO_TILES][16] = {",
        *tile_bytes_to_c_lines(logo),
        "};",
        "",
        "const uint8_t gSplashFallingStarTiles[SPLASH_FALLING_STAR_TILES][16] = {",
        *tile_bytes_to_c_lines(star),
        "};",
        "",
        "const uint8_t gSplashShootingStarTiles[SPLASH_SHOOTING_STAR_TILES][16] = {",
        *tile_bytes_to_c_lines(big_star),
        "};",
        "",
        "const uint8_t gSplashGameFreakPresentsTiles[SPLASH_GAMEFREAK_PRESENTS_TILES][16] = {",
        *tile_bytes_to_c_lines(presents),
        "};",
        "",
        "const uint8_t gSplashLegalTiles[SPLASH_LEGAL_TILES][16] = {",
        *tile_bytes_to_c_lines(legal),
        "};",
        "",
    ]

    (OUT / "splash_screen_data.h").write_text("\n".join(h_lines), encoding="ascii")
    (OUT / "splash_screen_data.c").write_text("\n".join(c_lines), encoding="ascii")

    print(
        "Wrote splash_screen_data.[ch]: "
        f"logo={logo_tiles}, star={star_tiles}, big_star={big_star_tiles}, "
        f"presents={presents_tiles}, legal={legal_tiles}"
    )


if __name__ == "__main__":
    main()
