#!/usr/bin/env python3
"""gen_tmhm_data.py — Generate .tmhm={...} initializers for base_stats.c.

Reads pokered-master/data/pokemon/base_stats/<species>.asm files,
extracts the `tmhm` macro learnset, and emits C designated-initializer
lines for each species indexed by national dex number (1-151).

Usage:
    python tools/gen_tmhm_data.py
    # Paste the output into base_stats.c as the .tmhm field.

    # Or redirect directly to a file to review:
    python tools/gen_tmhm_data.py > /tmp/tmhm_out.txt
"""

import os
import re
import glob

POKERED_MASTER = os.path.join(os.path.dirname(__file__), '..', 'pokered-master')
BASE_STATS_DIR = os.path.join(POKERED_MASTER, 'data', 'pokemon', 'base_stats')
DEX_CONSTANTS  = os.path.join(POKERED_MASTER, 'constants', 'pokedex_constants.asm')

# ------------------------------------------------------------------
# TM/HM table: index 0 = TM01, index 49 = TM50, 50 = HM01, 54 = HM05
# (mirrors item_constants.asm order)
# ------------------------------------------------------------------
TM_HM_MOVES = [
    # TM01-TM10
    'MEGA_PUNCH', 'RAZOR_WIND', 'SWORDS_DANCE', 'WHIRLWIND', 'MEGA_KICK',
    'TOXIC', 'HORN_DRILL', 'BODY_SLAM', 'TAKE_DOWN', 'DOUBLE_EDGE',
    # TM11-TM20
    'BUBBLEBEAM', 'WATER_GUN', 'ICE_BEAM', 'BLIZZARD', 'HYPER_BEAM',
    'PAY_DAY', 'SUBMISSION', 'COUNTER', 'SEISMIC_TOSS', 'RAGE',
    # TM21-TM30
    'MEGA_DRAIN', 'SOLARBEAM', 'DRAGON_RAGE', 'THUNDERBOLT', 'THUNDER',
    'EARTHQUAKE', 'FISSURE', 'DIG', 'PSYCHIC_M', 'TELEPORT',
    # TM31-TM40
    'MIMIC', 'DOUBLE_TEAM', 'REFLECT', 'BIDE', 'METRONOME',
    'SELFDESTRUCT', 'EGG_BOMB', 'FIRE_BLAST', 'SWIFT', 'SKULL_BASH',
    # TM41-TM50
    'SOFTBOILED', 'DREAM_EATER', 'SKY_ATTACK', 'REST', 'THUNDER_WAVE',
    'PSYWAVE', 'EXPLOSION', 'ROCK_SLIDE', 'TRI_ATTACK', 'SUBSTITUTE',
    # HM01-HM05 (indices 50-54)
    'CUT', 'FLY', 'SURF', 'STRENGTH', 'FLASH',
]

MOVE_TO_IDX = {name: i for i, name in enumerate(TM_HM_MOVES)}


def parse_dex_constants(path):
    """Return dict: 'DEX_BULBASAUR' -> 1, etc."""
    mapping = {}
    counter = 0
    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.strip()
            # Lines like:  const DEX_BULBASAUR
            m = re.match(r'const\s+(DEX_\w+)', line)
            if m:
                counter += 1
                mapping[m.group(1)] = counter
    return mapping


def parse_base_stats_file(path, dex_map):
    """Return (dex_id, tmhm_bits_7bytes, species_name) or None."""
    species_name = os.path.splitext(os.path.basename(path))[0]

    with open(path, encoding='utf-8', errors='replace') as f:
        content = f.read()

    # Extract dex id from first line: "db DEX_BULBASAUR ; pokedex id"
    dex_id = None
    for line in content.splitlines():
        m = re.match(r'\s*db\s+(DEX_\w+)', line)
        if m:
            key = m.group(1)
            dex_id = dex_map.get(key)
            break
    if dex_id is None:
        return None

    # Extract tmhm line(s): starts with "tmhm" keyword, may have \ continuations
    tmhm_section = ''
    in_tmhm = False
    for line in content.splitlines():
        stripped = line.strip()
        if re.match(r'tmhm\b', stripped):
            in_tmhm = True
            tmhm_section = stripped
        elif in_tmhm:
            if stripped.endswith('\\') or re.match(r'\w', stripped):
                tmhm_section += ' ' + stripped
            else:
                break
        if in_tmhm and not stripped.endswith('\\'):
            break

    # Parse move names from tmhm section
    # Remove "tmhm" keyword, backslashes, semicolons and after
    tmhm_section = re.sub(r'^tmhm\b', '', tmhm_section)
    tmhm_section = tmhm_section.replace('\\', '')
    tmhm_section = re.sub(r';.*', '', tmhm_section)
    tokens = re.split(r'[\s,]+', tmhm_section)

    bits = 0  # 64-bit int, we only use lower 55 bits
    for tok in tokens:
        tok = tok.strip()
        if not tok or tok == 'UNUSED':
            continue
        if tok in MOVE_TO_IDX:
            bits |= (1 << MOVE_TO_IDX[tok])
        else:
            print(f'  WARNING: unknown TM/HM move "{tok}" in {species_name}')

    # Pack into 7 bytes (LSB first)
    byte_vals = [(bits >> (8 * i)) & 0xFF for i in range(7)]
    return dex_id, byte_vals, species_name


def main():
    dex_map = parse_dex_constants(DEX_CONSTANTS)
    if not dex_map:
        print('ERROR: could not parse pokedex_constants.asm')
        return

    asm_files = glob.glob(os.path.join(BASE_STATS_DIR, '*.asm'))
    results = []
    for f in asm_files:
        r = parse_base_stats_file(f, dex_map)
        if r:
            results.append(r)

    results.sort(key=lambda x: x[0])

    print('/* TM/HM compatibility data — generated by tools/gen_tmhm_data.py */')
    print('/* Paste these .tmhm={...} fields into the gBaseStats entries.    */')
    print()
    for dex_id, byte_vals, name in results:
        hex_bytes = ', '.join(f'0x{b:02X}' for b in byte_vals)
        print(f'    /* [{dex_id:3d}] {name:<12} */  .tmhm = {{{hex_bytes}}},')


if __name__ == '__main__':
    main()
