/* connection_data.h -- Generated by tools/extract_connections.py */
#pragma once
#include <stdint.h>

/* One directional connection. dest_map==0xFF means no connection. */
typedef struct {
    uint8_t  dest_map;     /* destination map ID, 0xFF = none */
    int16_t  player_coord; /* fixed-axis coord when entering dest (tile units) */
    int16_t  adjust;       /* signed delta applied to the free axis (tile units) */
} map_conn_t;

typedef struct {
    map_conn_t north;
    map_conn_t south;
    map_conn_t west;
    map_conn_t east;
} map_connections_t;

#define NUM_MAP_CONNECTIONS 248
extern const map_connections_t gMapConnections[NUM_MAP_CONNECTIONS];
