/* connection_data.c -- Generated by tools/extract_connections.py */
#include "connection_data.h"

const map_connections_t gMapConnections[NUM_MAP_CONNECTIONS] = {
    [  0] = { .north={0x0C,  71,    0}, .south={0x20,   1,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PalletTown */
    [  1] = { .north={0x0D, 143,  -20}, .south={0x0C,   1,  -20}, .west={0x21,  78,  -16}, .east={0xFF,   0,    0} },  /* ViridianCity */
    [  2] = { .north={0xFF,   0,    0}, .south={0x0D,   1,  -20}, .west={0xFF,   0,    0}, .east={0x0E,   0,  -16} },  /* PewterCity */
    [  3] = { .north={0x23,  71,  -20}, .south={0x10,   1,  -20}, .west={0x0F, 178,  -16}, .east={0x14,   0,  -16} },  /* CeruleanCity */
    [  4] = { .north={0x15, 143,    0}, .south={0x17,   1,    0}, .west={0x13, 118,    0}, .east={0xFF,   0,    0} },  /* LavenderTown */
    [  5] = { .north={0x11,  71,  -20}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0x16,   0,  -16} },  /* VermilionCity */
    [  6] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x1B,  78,  -16}, .east={0x12,   0,  -16} },  /* CeladonCity */
    [  7] = { .north={0xFF,   0,    0}, .south={0x1E,   1,  -20}, .west={0x1D,  98,  -16}, .east={0x1A,   0,  -16} },  /* FuchsiaCity */
    [  8] = { .north={0x20, 179,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0x1F,   0,    0} },  /* CinnabarIsland */
    [  9] = { .north={0xFF,   0,    0}, .south={0x22,   1,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* IndigoPlateau */
    [ 10] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SaffronCity */
    [ 11] = { .north={0x10,  71,  -20}, .south={0x11,   1,  -20}, .west={0x12,  38,  -16}, .east={0x13,   0,  -16} },  /* SaffronCity */
    [ 12] = { .north={0x01,  71,   20}, .south={0x00,   1,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route1 */
    [ 13] = { .north={0x02,  71,   20}, .south={0x01,   1,   20}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route2 */
    [ 14] = { .north={0x0F,  35, -100}, .south={0xFF,   0,    0}, .west={0x02,  78,   16}, .east={0xFF,   0,    0} },  /* Route3 */
    [ 15] = { .north={0xFF,   0,    0}, .south={0x0E,   1,  100}, .west={0xFF,   0,    0}, .east={0x03,   0,   16} },  /* Route4 */
    [ 16] = { .north={0x03,  71,   20}, .south={0x0A,   1,   20}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route5 */
    [ 17] = { .north={0x0A,  71,   20}, .south={0x05,   1,   20}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route6 */
    [ 18] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x06,  98,   16}, .east={0x0A,   0,   16} },  /* Route7 */
    [ 19] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x0A,  78,   16}, .east={0x04,   0,    0} },  /* Route8 */
    [ 20] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x03,  78,   16}, .east={0x15,   0,    0} },  /* Route9 */
    [ 21] = { .north={0xFF,   0,    0}, .south={0x04,   1,    0}, .west={0x14, 118,    0}, .east={0xFF,   0,    0} },  /* Route10 */
    [ 22] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x05,  78,   16}, .east={0x17,   0,  108} },  /* Route11 */
    [ 23] = { .north={0x04,  35,    0}, .south={0x18,   1,   80}, .west={0x16, 118, -108}, .east={0xFF,   0,    0} },  /* Route12 */
    [ 24] = { .north={0x17, 215,  -80}, .south={0xFF,   0,    0}, .west={0x19,  38,    0}, .east={0xFF,   0,    0} },  /* Route13 */
    [ 25] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x1A, 118,  -72}, .east={0x18,   0,    0} },  /* Route14 */
    [ 26] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x07,  78,   16}, .east={0x19,   0,   72} },  /* Route15 */
    [ 27] = { .north={0xFF,   0,    0}, .south={0x1C,   1,    0}, .west={0xFF,   0,    0}, .east={0x06,   0,   16} },  /* Route16 */
    [ 28] = { .north={0x1B,  35,    0}, .south={0x1D,   1,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route17 */
    [ 29] = { .north={0x1C, 287,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0x07,   0,   16} },  /* Route18 */
    [ 30] = { .north={0x07,  71,   20}, .south={0xFF,   0,    0}, .west={0x1F, 198,  -72}, .east={0xFF,   0,    0} },  /* Route19 */
    [ 31] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x08,  38,    0}, .east={0x1E,   0,   72} },  /* Route20 */
    [ 32] = { .north={0x00,  35,    0}, .south={0x08,   1,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route21 */
    [ 33] = { .north={0x22, 287,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0x01,   0,   16} },  /* Route22 */
    [ 34] = { .north={0x09,  35,    0}, .south={0x21,   1,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route23 */
    [ 35] = { .north={0xFF,   0,    0}, .south={0x03,   1,   20}, .west={0xFF,   0,    0}, .east={0x24,   0,    0} },  /* Route24 */
    [ 36] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0x23,  38,    0}, .east={0xFF,   0,    0} },  /* Route25 */
    [ 37] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RedsHouse1F */
    [ 38] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RedsHouse2F */
    [ 39] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* BluesHouse */
    [ 40] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* OaksLab */
    [ 41] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianPokecenter */
    [ 42] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianMart */
    [ 43] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianSchoolHouse */
    [ 44] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianNicknameHouse */
    [ 45] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianGym */
    [ 46] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* DiglettsCaveRoute2 */
    [ 47] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianForestNorthGate */
    [ 48] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route2TradeHouse */
    [ 49] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route2Gate */
    [ 50] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianForestSouthGate */
    [ 51] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ViridianForest */
    [ 52] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Museum1F */
    [ 53] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Museum2F */
    [ 54] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PewterGym */
    [ 55] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PewterNidoranHouse */
    [ 56] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PewterMart */
    [ 57] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PewterSpeechHouse */
    [ 58] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PewterPokecenter */
    [ 59] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* MtMoon1F */
    [ 60] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* MtMoonB1F */
    [ 61] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* MtMoonB2F */
    [ 62] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanTrashedHouse */
    [ 63] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanTradeHouse */
    [ 64] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanPokecenter */
    [ 65] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanGym */
    [ 66] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* BikeShop */
    [ 67] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanMart */
    [ 68] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* MtMoonPokecenter */
    [ 69] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanTrashedHouse */
    [ 70] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route5Gate */
    [ 71] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathRoute5 */
    [ 72] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Daycare */
    [ 73] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route6Gate */
    [ 74] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathRoute6 */
    [ 75] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathRoute6 */
    [ 76] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route7Gate */
    [ 77] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathRoute7 */
    [ 78] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathRoute7Copy */
    [ 79] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route8Gate */
    [ 80] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathRoute8 */
    [ 81] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RockTunnelPokecenter */
    [ 82] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RockTunnel1F */
    [ 83] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PowerPlant */
    [ 84] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route11Gate1F */
    [ 85] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* DiglettsCaveRoute11 */
    [ 86] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route11Gate2F */
    [ 87] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route12Gate1F */
    [ 88] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* BillsHouse */
    [ 89] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VermilionPokecenter */
    [ 90] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonFanClub */
    [ 91] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VermilionMart */
    [ 92] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VermilionGym */
    [ 93] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VermilionPidgeyHouse */
    [ 94] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VermilionDock */
    [ 95] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnne1F */
    [ 96] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnne2F */
    [ 97] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnne3F */
    [ 98] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnneB1F */
    [ 99] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnneBow */
    [100] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnneKitchen */
    [101] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnneCaptainsRoom */
    [102] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnne1FRooms */
    [103] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnne2FRooms */
    [104] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SSAnneB1FRooms */
    [105] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [106] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [107] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [108] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VictoryRoad1F */
    [109] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [110] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [111] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [112] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [113] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [114] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [115] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [116] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [117] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LancesRoom */
    [118] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* HallOfFame */
    [119] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathNorthSouth */
    [120] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* ChampionsRoom */
    [121] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* UndergroundPathWestEast */
    [122] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMart1F */
    [123] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMart2F */
    [124] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMart3F */
    [125] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMart4F */
    [126] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMartRoof */
    [127] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMartElevator */
    [128] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMansion1F */
    [129] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMansion2F */
    [130] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMansion3F */
    [131] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMansionRoof */
    [132] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMansionRoofHouse */
    [133] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonPokecenter */
    [134] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonGym */
    [135] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* GameCorner */
    [136] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonMart5F */
    [137] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* GameCornerPrizeRoom */
    [138] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonDiner */
    [139] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonChiefHouse */
    [140] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeladonHotel */
    [141] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LavenderPokecenter */
    [142] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonTower1F */
    [143] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonTower2F */
    [144] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonTower3F */
    [145] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonTower4F */
    [146] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonTower5F */
    [147] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonTower6F */
    [148] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonTower7F */
    [149] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* MrFujisHouse */
    [150] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LavenderMart */
    [151] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LavenderCuboneHouse */
    [152] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* FuchsiaMart */
    [153] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* FuchsiaBillsGrandpasHouse */
    [154] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* FuchsiaPokecenter */
    [155] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* WardensHouse */
    [156] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneGate */
    [157] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* FuchsiaGym */
    [158] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* FuchsiaMeetingRoom */
    [159] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SeafoamIslandsB1F */
    [160] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SeafoamIslandsB2F */
    [161] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SeafoamIslandsB3F */
    [162] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SeafoamIslandsB4F */
    [163] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VermilionOldRodHouse */
    [164] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* FuchsiaGoodRodHouse */
    [165] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonMansion1F */
    [166] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarGym */
    [167] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarLab */
    [168] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarLabTradeRoom */
    [169] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarLabMetronomeRoom */
    [170] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarLabFossilRoom */
    [171] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarPokecenter */
    [172] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarMart */
    [173] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CinnabarMart */
    [174] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* IndigoPlateauLobby */
    [175] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CopycatsHouse1F */
    [176] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CopycatsHouse2F */
    [177] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* FightingDojo */
    [178] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SaffronGym */
    [179] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SaffronPidgeyHouse */
    [180] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SaffronMart */
    [181] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo1F */
    [182] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SaffronPokecenter */
    [183] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* MrPsychicsHouse */
    [184] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route15Gate1F */
    [185] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route15Gate2F */
    [186] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route16Gate1F */
    [187] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route16Gate2F */
    [188] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route16FlyHouse */
    [189] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route12SuperRodHouse */
    [190] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route18Gate1F */
    [191] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route18Gate2F */
    [192] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SeafoamIslands1F */
    [193] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route22Gate */
    [194] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VictoryRoad2F */
    [195] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route12Gate2F */
    [196] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VermilionTradeHouse */
    [197] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* DiglettsCave */
    [198] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* VictoryRoad3F */
    [199] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutB1F */
    [200] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutB2F */
    [201] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutB3F */
    [202] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutB4F */
    [203] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutElevator */
    [204] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutElevator */
    [205] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutElevator */
    [206] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RocketHideoutElevator */
    [207] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo2F */
    [208] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo3F */
    [209] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo4F */
    [210] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo5F */
    [211] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo6F */
    [212] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo7F */
    [213] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo8F */
    [214] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonMansion2F */
    [215] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonMansion3F */
    [216] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* PokemonMansionB1F */
    [217] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneEast */
    [218] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneNorth */
    [219] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneWest */
    [220] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneCenter */
    [221] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneCenterRestHouse */
    [222] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneSecretHouse */
    [223] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneWestRestHouse */
    [224] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneEastRestHouse */
    [225] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SafariZoneNorthRestHouse */
    [226] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanCave2F */
    [227] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanCaveB1F */
    [228] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanCave1F */
    [229] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* NameRatersHouse */
    [230] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* CeruleanBadgeHouse */
    [231] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Route16Gate1F */
    [232] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* RockTunnelB1F */
    [233] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo9F */
    [234] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo10F */
    [235] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo11F */
    [236] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCoElevator */
    [237] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo2F */
    [238] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo2F */
    [239] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* TradeCenter */
    [240] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* Colosseum */
    [241] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo2F */
    [242] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo2F */
    [243] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo2F */
    [244] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* SilphCo2F */
    [245] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* LoreleisRoom */
    [246] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* BrunosRoom */
    [247] = { .north={0xFF,   0,    0}, .south={0xFF,   0,    0}, .west={0xFF,   0,    0}, .east={0xFF,   0,    0} },  /* AgathasRoom */
};
