/* cry_data.h — Pokémon cry note data extracted from pokered-master.
 * Generated by tools/extract_cries.py — DO NOT EDIT.
 *
 * ALWAYS refer to pokered-master audio/sfx/cry*.asm before modifying.
 */
#pragma once
#include <stdint.h>

/* One square (CH1/CH2) note */
typedef struct {
    uint8_t  len;    /* note length (1-15 frames base) */
    uint8_t  vol;    /* initial volume 0-15 */
    uint8_t  fade;   /* envelope decrease pace (0=off) */
    uint16_t freq;   /* 11-bit GB freq register value */
} cry_sq_note_t;

/* One noise (CH4) note */
typedef struct {
    uint8_t len;   /* note length */
    uint8_t vol;
    uint8_t fade;
    uint8_t nr43;  /* NR43: shift<<4 | width_bit<<3 | divisor */
} cry_noise_note_t;

/* Square channel descriptor */
typedef struct {
    uint8_t              duty_pattern; /* (d0<<6)|(d1<<4)|(d2<<2)|d3 */
    uint8_t              rotate_duty;  /* 1=duty_cycle_pattern, 0=fixed */
    uint8_t              n_notes;
    const cry_sq_note_t *notes;
} cry_sq_ch_t;

/* Noise channel descriptor */
typedef struct {
    uint8_t                  n_notes;
    const cry_noise_note_t  *notes;
} cry_noise_ch_t;

/* Full 3-channel cry definition */
typedef struct {
    cry_sq_ch_t    ch5;  /* square CH1 → audio ch[0] */
    cry_sq_ch_t    ch6;  /* square CH2 → audio ch[1] */
    cry_noise_ch_t ch8;  /* noise  CH4 → audio ch[3] */
} cry_def_t;

/* Per-Pokémon cry parameters (internal species 1..191, table is 0-based) */
typedef struct {
    uint8_t base_cry;  /* index into g_cry_defs[0..37] */
    int8_t  pitch_mod; /* wFrequencyModifier: added to each note freq */
    uint8_t tempo_mod; /* wTempoModifier: sfx_tempo = tempo_mod + 0x80 */
} pokemon_cry_t;

#define NUM_BASE_CRIES      38
#define NUM_POKEMON_CRIES   190

/* Base cry definitions indexed 0..37 (cry00..cry25 hex) */
extern const cry_def_t     g_cry_defs[NUM_BASE_CRIES];

/* Per-species lookup: index = (internal_species_id - 1) */
extern const pokemon_cry_t g_pokemon_cries[NUM_POKEMON_CRIES];
