#pragma once
/* dex_data.h — Pokédex entry data for all 151 Pokémon.
 * Generated by tools/gen_dex_data.py from pokered-master ASM.
 * Index gDexEntries[dex_number], dex_number 1-151. [0] unused.
 */
#include <stdint.h>

typedef struct {
    const char *category;    /* species category, e.g. "SEED" */
    uint8_t     height_ft;
    uint8_t     height_in;
    uint16_t    weight;      /* tenths of a pound */
    const char *description; /* ASCII, \\f = page break */
} dex_entry_t;

#define NUM_DEX_ENTRIES 152
extern const dex_entry_t gDexEntries[NUM_DEX_ENTRIES];
