#pragma once
/* intro_scene_data.h -- AUTO-GENERATED by tools/extract_intro_scene.py. */
#include <stdint.h>

#define INTRO_GENGAR_BACK_TILES     94
#define INTRO_NIDORINO_FRONT_TILES 108
#define INTRO_GENGAR_TILEMAP_TILES  49

extern const uint8_t gIntroGengarBackTiles[INTRO_GENGAR_BACK_TILES][16];
extern const uint8_t gIntroNidorinoFrontTiles[INTRO_NIDORINO_FRONT_TILES][16];
extern const uint8_t gIntroGengarTilemap1[INTRO_GENGAR_TILEMAP_TILES];
extern const uint8_t gIntroGengarTilemap2[INTRO_GENGAR_TILEMAP_TILES];
extern const uint8_t gIntroGengarTilemap3[INTRO_GENGAR_TILEMAP_TILES];
