#pragma once
/* move_anim_tiles.h -- AUTO-GENERATED by tools/extract_move_anim_tiles.py. */
#include <stdint.h>

#define MOVE_ANIM_TILESET0_TILES 79
#define MOVE_ANIM_TILESET1_TILES 79
#define MOVE_ANIM_TILESET2_TILES 64

extern const uint8_t gMoveAnimTileset0[MOVE_ANIM_TILESET0_TILES][16];
extern const uint8_t gMoveAnimTileset1[MOVE_ANIM_TILESET1_TILES][16];
