#pragma once
/* move_sfx_structs.h -- AUTO-GENERATED by tools/extract_move_sfx_structs.py. */
#include <stdint.h>

typedef enum {
    MOVE_SFX_CMD_DUTY_CYCLE = 0,
    MOVE_SFX_CMD_DUTY_CYCLE_PATTERN = 1,
    MOVE_SFX_CMD_PITCH_SWEEP = 2,
    MOVE_SFX_CMD_SQUARE_NOTE = 3,
    MOVE_SFX_CMD_NOISE_NOTE = 4,
    MOVE_SFX_CMD_SOUND_LOOP = 5,
    MOVE_SFX_CMD_SOUND_RET = 6,
} move_sfx_cmd_type_t;

typedef struct {
    uint8_t type;
    int16_t p0;
    int16_t p1;
    int16_t p2;
    int16_t p3;
} move_sfx_cmd_t;

typedef struct {
    uint8_t hw_channel;
    const char *label;
    const move_sfx_cmd_t *cmds;
    uint16_t cmd_count;
} move_sfx_channel_def_t;

typedef struct {
    const char *symbol;
    uint8_t bank;
    const move_sfx_channel_def_t *channels;
    uint8_t channel_count;
} move_sfx_def_t;

extern const move_sfx_def_t gMoveSfxStructs[];
extern const uint16_t gMoveSfxStructCount;
