#pragma once
/* move_sfx_data.h -- AUTO-GENERATED by tools/extract_move_sfx.py. */
#include <stdint.h>

typedef struct {
    const char *sfx_symbol; /* ASM token, e.g. SFX_BATTLE_0B */
    uint8_t pitch_mod;
    uint8_t tempo_mod;
} move_sfx_data_t;

#define MOVE_SFX_DATA_COUNT 166

extern const move_sfx_data_t gMoveSfxData[MOVE_SFX_DATA_COUNT];
