/* move_sfx_structs.c -- AUTO-GENERATED by tools/extract_move_sfx_structs.py. */
#include "move_sfx_structs.h"

static const move_sfx_cmd_t sfx_SFX_Pound_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 10, 1, 34 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_POUND_channels[] = {
    { 8, "SFX_Pound_Ch8", sfx_SFX_Pound_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Pound_Ch8_cmds)/sizeof(sfx_SFX_Pound_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_0C_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 8, -7, 17 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 15, -7, 18 },
    { MOVE_SFX_CMD_NOISE_NOTE, 10, 15, 1, 85 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_0C_channels[] = {
    { 8, "SFX_Battle_0C_Ch8", sfx_SFX_Battle_0C_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_0C_Ch8_cmds)/sizeof(sfx_SFX_Battle_0C_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Doubleslap_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 51 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_DOUBLESLAP_channels[] = {
    { 8, "SFX_Doubleslap_Ch8", sfx_SFX_Doubleslap_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Doubleslap_Ch8_cmds)/sizeof(sfx_SFX_Doubleslap_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_0B_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 84 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_0B_channels[] = {
    { 8, "SFX_Battle_0B_Ch8", sfx_SFX_Battle_0B_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_0B_Ch8_cmds)/sizeof(sfx_SFX_Battle_0B_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_0D_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 8, -7, 52 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 2, 53 },
    { MOVE_SFX_CMD_NOISE_NOTE, 10, 15, 1, 85 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_0D_channels[] = {
    { 8, "SFX_Battle_0D_Ch8", sfx_SFX_Battle_0D_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_0D_Ch8_cmds)/sizeof(sfx_SFX_Battle_0D_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Silph_Scope_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 0, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 13, 2, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 13, 2, 1856 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 13, 2, 1920 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 13, 2, 1984 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 14, 1, 2016 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 1, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_SILPH_SCOPE_channels[] = {
    { 5, "SFX_Silph_Scope_Ch5", sfx_SFX_Silph_Scope_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Silph_Scope_Ch5_cmds)/sizeof(sfx_SFX_Silph_Scope_Ch5_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Damage_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 15, 4, 68 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 15, 4, 20 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 1, 50 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_DAMAGE_channels[] = {
    { 8, "SFX_Damage_Ch8", sfx_SFX_Damage_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Damage_Ch8_cmds)/sizeof(sfx_SFX_Damage_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_0F_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 14, 1, 75 },
    { MOVE_SFX_CMD_NOISE_NOTE, 10, 15, 1, 68 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 14, 1, 58 },
    { MOVE_SFX_CMD_NOISE_NOTE, 6, 15, 1, 52 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_0F_channels[] = {
    { 8, "SFX_Battle_0F_Ch8", sfx_SFX_Battle_0F_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_0F_Ch8_cmds)/sizeof(sfx_SFX_Battle_0F_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_0E_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 9, -7, 35 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 33 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_0E_channels[] = {
    { 8, "SFX_Battle_0E_Ch8", sfx_SFX_Battle_0E_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_0E_Ch8_cmds)/sizeof(sfx_SFX_Battle_0E_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Not_Very_Effective_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 8, -7, 85 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 15, 4, 68 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 4, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 33 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_NOT_VERY_EFFECTIVE_channels[] = {
    { 8, "SFX_Not_Very_Effective_Ch8", sfx_SFX_Not_Very_Effective_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Not_Very_Effective_Ch8_cmds)/sizeof(sfx_SFX_Not_Very_Effective_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_12_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 4, -7, 35 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 12, 4, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 6, 15, 2, 35 },
    { MOVE_SFX_CMD_SOUND_LOOP, 4, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_12_channels[] = {
    { 8, "SFX_Battle_12_Ch8", sfx_SFX_Battle_12_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_12_Ch8_cmds)/sizeof(sfx_SFX_Battle_12_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_13_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 4, -7, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 12, 4, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 6, 15, 2, 35 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 34 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_13_channels[] = {
    { 8, "SFX_Battle_13_Ch8", sfx_SFX_Battle_13_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_13_Ch8_cmds)/sizeof(sfx_SFX_Battle_13_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_14_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, -7, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 4, 67 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 2, 84 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 101 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_14_channels[] = {
    { 8, "SFX_Battle_14_Ch8", sfx_SFX_Battle_14_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_14_Ch8_cmds)/sizeof(sfx_SFX_Battle_14_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_22_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 13, 2, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 67 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_22_channels[] = {
    { 8, "SFX_Battle_22_Ch8", sfx_SFX_Battle_22_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_22_Ch8_cmds)/sizeof(sfx_SFX_Battle_22_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Vine_Whip_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 12, 2, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 15, 2, 33 },
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 14, 2, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 12, 2, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 9, 2, 18 },
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 11, 2, 49 },
    { MOVE_SFX_CMD_NOISE_NOTE, 12, 9, 1, 16 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 2, 65 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_VINE_WHIP_channels[] = {
    { 8, "SFX_Vine_Whip_Ch8", sfx_SFX_Vine_Whip_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Vine_Whip_Ch8_cmds)/sizeof(sfx_SFX_Vine_Whip_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_20_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 12, 15, 1, 84 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 100 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_20_channels[] = {
    { 8, "SFX_Battle_20_Ch8", sfx_SFX_Battle_20_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_20_Ch8_cmds)/sizeof(sfx_SFX_Battle_20_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_17_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 9, 4, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 11, 4, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 15, 1, 68 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 85 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_17_channels[] = {
    { 8, "SFX_Battle_17_Ch8", sfx_SFX_Battle_17_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_17_Ch8_cmds)/sizeof(sfx_SFX_Battle_17_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Super_Effective_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 15, 1, 52 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 100 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_SUPER_EFFECTIVE_channels[] = {
    { 8, "SFX_Super_Effective_Ch8", sfx_SFX_Super_Effective_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Super_Effective_Ch8_cmds)/sizeof(sfx_SFX_Super_Effective_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_21_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 15, 1, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 12, 1, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 10, 1, 49 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 8, 2, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 52 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_21_channels[] = {
    { 8, "SFX_Battle_21_Ch8", sfx_SFX_Battle_21_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_21_Ch8_cmds)/sizeof(sfx_SFX_Battle_21_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_1B_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 15, 1, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 18 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_1B_channels[] = {
    { 8, "SFX_Battle_1B_Ch8", sfx_SFX_Battle_1B_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_1B_Ch8_cmds)/sizeof(sfx_SFX_Battle_1B_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_18_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 15, -7, 85 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 101 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_18_channels[] = {
    { 8, "SFX_Battle_18_Ch8", sfx_SFX_Battle_18_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_18_Ch8_cmds)/sizeof(sfx_SFX_Battle_18_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_1E_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 0, 0, 0, 0 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 3, -2, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 15, 2, 512 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 2, 2, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 14, 2, 512 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 0, 8, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_1E_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 0, 13, 1, 66 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 10, 1, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 0, 13, 1, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 6, 10, 1, 50 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_1E_channels[] = {
    { 5, "SFX_Battle_1E_Ch5", sfx_SFX_Battle_1E_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_1E_Ch5_cmds)/sizeof(sfx_SFX_Battle_1E_Ch5_cmds[0])) },
    { 8, "SFX_Battle_1E_Ch8", sfx_SFX_Battle_1E_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_1E_Ch8_cmds)/sizeof(sfx_SFX_Battle_1E_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Horn_Drill_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 9, 2, 49 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 11, 2, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 12, 2, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 1, 84 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_HORN_DRILL_channels[] = {
    { 8, "SFX_Horn_Drill_Ch8", sfx_SFX_Horn_Drill_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Horn_Drill_Ch8_cmds)/sizeof(sfx_SFX_Horn_Drill_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_19_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 8, 4, 67 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 12, 4, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 2, 52 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_19_channels[] = {
    { 8, "SFX_Battle_19_Ch8", sfx_SFX_Battle_19_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_19_Ch8_cmds)/sizeof(sfx_SFX_Battle_19_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_31_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2016 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2016 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2016 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2016 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 2, 2016 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_31_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 3, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2018 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2017 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2018 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 2017 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 2, 2018 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_31_channels[] = {
    { 5, "SFX_Battle_31_Ch5", sfx_SFX_Battle_31_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_31_Ch5_cmds)/sizeof(sfx_SFX_Battle_31_Ch5_cmds[0])) },
    { 6, "SFX_Battle_31_Ch6", sfx_SFX_Battle_31_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_31_Ch6_cmds)/sizeof(sfx_SFX_Battle_31_Ch6_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_35_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_35_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_35_channels[] = {
    { 5, "SFX_Battle_35_Ch5", sfx_SFX_Battle_35_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_35_Ch5_cmds)/sizeof(sfx_SFX_Battle_35_Ch5_cmds[0])) },
    { 6, "SFX_Battle_35_Ch6", sfx_SFX_Battle_35_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_35_Ch6_cmds)/sizeof(sfx_SFX_Battle_35_Ch6_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_27_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 3, -7, 1984 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 13, -7, 1984 },
    { MOVE_SFX_CMD_SOUND_LOOP, 4, 2, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 13, 1, 1984 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_27_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 3, 0, 3 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 2, -7, 1992 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 12, -7, 1991 },
    { MOVE_SFX_CMD_SOUND_LOOP, 4, 2, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 12, 1, 1992 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_27_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 9, 7, 18 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 10, 1, 17 },
    { MOVE_SFX_CMD_SOUND_LOOP, 10, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_27_channels[] = {
    { 5, "SFX_Battle_27_Ch5", sfx_SFX_Battle_27_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_27_Ch5_cmds)/sizeof(sfx_SFX_Battle_27_Ch5_cmds[0])) },
    { 6, "SFX_Battle_27_Ch6", sfx_SFX_Battle_27_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_27_Ch6_cmds)/sizeof(sfx_SFX_Battle_27_Ch6_cmds[0])) },
    { 8, "SFX_Battle_27_Ch8", sfx_SFX_Battle_27_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_27_Ch8_cmds)/sizeof(sfx_SFX_Battle_27_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2A_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 0, 3, 2, 1 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 15, 4, 1536 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 12, 4, 1280 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 5, 11, 5, 1536 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 13, 14, 2, 1728 },
    { MOVE_SFX_CMD_SOUND_LOOP, 3, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 13, 1, 1536 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2A_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 0, 3, 1 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 5, 14, 4, 1504 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 11, 4, 1248 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 10, 5, 1512 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 14, 13, 1, 1696 },
    { MOVE_SFX_CMD_SOUND_LOOP, 3, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2A_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 5, 12, 3, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 9, 2, 67 },
    { MOVE_SFX_CMD_NOISE_NOTE, 10, 11, 5, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 12, 3, 50 },
    { MOVE_SFX_CMD_SOUND_LOOP, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_2A_channels[] = {
    { 5, "SFX_Battle_2A_Ch5", sfx_SFX_Battle_2A_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2A_Ch5_cmds)/sizeof(sfx_SFX_Battle_2A_Ch5_cmds[0])) },
    { 6, "SFX_Battle_2A_Ch6", sfx_SFX_Battle_2A_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2A_Ch6_cmds)/sizeof(sfx_SFX_Battle_2A_Ch6_cmds[0])) },
    { 8, "SFX_Battle_2A_Ch8", sfx_SFX_Battle_2A_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2A_Ch8_cmds)/sizeof(sfx_SFX_Battle_2A_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_29_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 3, 0, 2, 1 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 11, 15, 3, 288 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 9, 13, 3, 336 },
    { MOVE_SFX_CMD_SOUND_LOOP, 5, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 14, 3, 304 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 12, 2, 272 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_29_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 10, 15, 3, 53 },
    { MOVE_SFX_CMD_NOISE_NOTE, 14, 15, 6, 69 },
    { MOVE_SFX_CMD_SOUND_LOOP, 4, 0, 0, 0 },
    { MOVE_SFX_CMD_NOISE_NOTE, 12, 15, 4, 188 },
    { MOVE_SFX_CMD_NOISE_NOTE, 12, 15, 5, 156 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 4, 172 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_29_channels[] = {
    { 5, "SFX_Battle_29_Ch5", sfx_SFX_Battle_29_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_29_Ch5_cmds)/sizeof(sfx_SFX_Battle_29_Ch5_cmds[0])) },
    { 8, "SFX_Battle_29_Ch8", sfx_SFX_Battle_29_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_29_Ch8_cmds)/sizeof(sfx_SFX_Battle_29_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_24_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 1, 0, 0, 0 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 9, 7, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 2, 1792 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 0, 8, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_24_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 3, -7, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 33 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_24_channels[] = {
    { 5, "SFX_Battle_24_Ch5", sfx_SFX_Battle_24_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_24_Ch5_cmds)/sizeof(sfx_SFX_Battle_24_Ch5_cmds[0])) },
    { 8, "SFX_Battle_24_Ch8", sfx_SFX_Battle_24_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_24_Ch8_cmds)/sizeof(sfx_SFX_Battle_24_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2C_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 0, 3, 2, 1 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 4, 1280 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 12, 4, 1024 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 14, 2, 1472 },
    { MOVE_SFX_CMD_SOUND_LOOP, 3, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2C_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 0, 3, 1 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 7, 14, 4, 1072 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 11, 4, 816 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 10, 2, 1080 },
    { MOVE_SFX_CMD_SOUND_LOOP, 4, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2C_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 9, 15, 4, 68 },
    { MOVE_SFX_CMD_NOISE_NOTE, 9, 15, 2, 67 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 4, 66 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 4, 65 },
    { MOVE_SFX_CMD_SOUND_LOOP, 3, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_2C_channels[] = {
    { 5, "SFX_Battle_2C_Ch5", sfx_SFX_Battle_2C_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2C_Ch5_cmds)/sizeof(sfx_SFX_Battle_2C_Ch5_cmds[0])) },
    { 6, "SFX_Battle_2C_Ch6", sfx_SFX_Battle_2C_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2C_Ch6_cmds)/sizeof(sfx_SFX_Battle_2C_Ch6_cmds[0])) },
    { 8, "SFX_Battle_2C_Ch8", sfx_SFX_Battle_2C_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2C_Ch8_cmds)/sizeof(sfx_SFX_Battle_2C_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_28_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 0, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 15, 1, 1984 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 15, 1, 1792 },
    { MOVE_SFX_CMD_SOUND_LOOP, 12, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_28_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 3, 0, 3 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 14, 1, 1985 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 0, 14, 1, 1793 },
    { MOVE_SFX_CMD_SOUND_LOOP, 12, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_28_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 13, 1, 73 },
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 13, 1, 41 },
    { MOVE_SFX_CMD_SOUND_LOOP, 6, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_28_channels[] = {
    { 5, "SFX_Battle_28_Ch5", sfx_SFX_Battle_28_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_28_Ch5_cmds)/sizeof(sfx_SFX_Battle_28_Ch5_cmds[0])) },
    { 6, "SFX_Battle_28_Ch6", sfx_SFX_Battle_28_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_28_Ch6_cmds)/sizeof(sfx_SFX_Battle_28_Ch6_cmds[0])) },
    { 8, "SFX_Battle_28_Ch8", sfx_SFX_Battle_28_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_28_Ch8_cmds)/sizeof(sfx_SFX_Battle_28_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Psybeam_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 2, 0, 1 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 15, 1, 1600 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 15, 3, 1664 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 15, 2, 1568 },
    { MOVE_SFX_CMD_SOUND_LOOP, 4, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 15, 1, 1600 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Psybeam_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 3, 0, 3 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 15, 3, 1393 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 7, 14, 3, 1329 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 15, 1, 1361 },
    { MOVE_SFX_CMD_SOUND_LOOP, 4, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 10, 15, 1, 1393 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Psybeam_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 13, 1, 74 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 13, 2, 42 },
    { MOVE_SFX_CMD_SOUND_LOOP, 21, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_PSYBEAM_channels[] = {
    { 5, "SFX_Psybeam_Ch5", sfx_SFX_Psybeam_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Psybeam_Ch5_cmds)/sizeof(sfx_SFX_Psybeam_Ch5_cmds[0])) },
    { 6, "SFX_Psybeam_Ch6", sfx_SFX_Psybeam_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Psybeam_Ch6_cmds)/sizeof(sfx_SFX_Psybeam_Ch6_cmds[0])) },
    { 8, "SFX_Psybeam_Ch8", sfx_SFX_Psybeam_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Psybeam_Ch8_cmds)/sizeof(sfx_SFX_Psybeam_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_36_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 0, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1920 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1936 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1952 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1968 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1984 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 2000 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 2016 },
    { MOVE_SFX_CMD_SOUND_LOOP, 12, 12, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 1, 1792 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_36_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 3, 0, 3 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1921 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1793 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1937 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1793 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1953 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1793 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1969 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1793 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1985 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1793 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 2001 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 1793 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 2017 },
    { MOVE_SFX_CMD_SOUND_LOOP, 12, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 1, 1793 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_36_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 13, 1, 73 },
    { MOVE_SFX_CMD_NOISE_NOTE, 1, 13, 1, 41 },
    { MOVE_SFX_CMD_SOUND_LOOP, 26, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_36_channels[] = {
    { 5, "SFX_Battle_36_Ch5", sfx_SFX_Battle_36_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_36_Ch5_cmds)/sizeof(sfx_SFX_Battle_36_Ch5_cmds[0])) },
    { 6, "SFX_Battle_36_Ch6", sfx_SFX_Battle_36_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_36_Ch6_cmds)/sizeof(sfx_SFX_Battle_36_Ch6_cmds[0])) },
    { 8, "SFX_Battle_36_Ch8", sfx_SFX_Battle_36_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_36_Ch8_cmds)/sizeof(sfx_SFX_Battle_36_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Peck_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 10, 1, 18 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_PECK_channels[] = {
    { 8, "SFX_Peck_Ch8", sfx_SFX_Peck_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Peck_Ch8_cmds)/sizeof(sfx_SFX_Peck_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_23_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 15, 2, 67 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 11, 5, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 9, 8, 6, 49 },
    { MOVE_SFX_CMD_NOISE_NOTE, 7, 6, 4, 0 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 85 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_23_channels[] = {
    { 8, "SFX_Battle_23_Ch8", sfx_SFX_Battle_23_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_23_Ch8_cmds)/sizeof(sfx_SFX_Battle_23_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_26_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 10, 15, -7, 80 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, -7, 81 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 2, 81 },
    { MOVE_SFX_CMD_NOISE_NOTE, 6, 15, -7, 82 },
    { MOVE_SFX_CMD_NOISE_NOTE, 6, 15, -7, 83 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, -7, 84 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 84 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_26_channels[] = {
    { 8, "SFX_Battle_26_Ch8", sfx_SFX_Battle_26_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_26_Ch8_cmds)/sizeof(sfx_SFX_Battle_26_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_25_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 4, -7, 65 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 8, -7, 65 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 12, -7, 65 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, 2, 66 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 65 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_25_channels[] = {
    { 8, "SFX_Battle_25_Ch8", sfx_SFX_Battle_25_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_25_Ch8_cmds)/sizeof(sfx_SFX_Battle_25_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2E_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 0, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 15, 1, 512 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 15, 1, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 15, 1, 1280 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 5, 15, 1, 2032 },
    { MOVE_SFX_CMD_SOUND_LOOP, 8, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2E_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 3, 0, 3 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 2, 14, 1, 770 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 14, 1, 2034 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 14, 1, 1538 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 5, 14, 1, 1794 },
    { MOVE_SFX_CMD_SOUND_LOOP, 8, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2E_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 13, 3, 16 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 13, 3, 17 },
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 13, 2, 16 },
    { MOVE_SFX_CMD_NOISE_NOTE, 5, 13, 2, 18 },
    { MOVE_SFX_CMD_SOUND_LOOP, 9, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_2E_channels[] = {
    { 5, "SFX_Battle_2E_Ch5", sfx_SFX_Battle_2E_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2E_Ch5_cmds)/sizeof(sfx_SFX_Battle_2E_Ch5_cmds[0])) },
    { 6, "SFX_Battle_2E_Ch6", sfx_SFX_Battle_2E_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2E_Ch6_cmds)/sizeof(sfx_SFX_Battle_2E_Ch6_cmds[0])) },
    { 8, "SFX_Battle_2E_Ch8", sfx_SFX_Battle_2E_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2E_Ch8_cmds)/sizeof(sfx_SFX_Battle_2E_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_1C_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 2, 12, 2, 1 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 4, 1 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 2, 1 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_1C_channels[] = {
    { 8, "SFX_Battle_1C_Ch8", sfx_SFX_Battle_1C_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_1C_Ch8_cmds)/sizeof(sfx_SFX_Battle_1C_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2F_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 0, 2, 2, 3 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 15, 1, 2032 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 15, 2, 512 },
    { MOVE_SFX_CMD_SOUND_LOOP, 8, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2F_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 3, 0, 3 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 14, 2, 514 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 4, 14, 1, 2018 },
    { MOVE_SFX_CMD_SOUND_LOOP, 9, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2F_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 15, -7, 67 },
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 15, 2, 68 },
    { MOVE_SFX_CMD_SOUND_LOOP, 9, 0, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_2F_channels[] = {
    { 5, "SFX_Battle_2F_Ch5", sfx_SFX_Battle_2F_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2F_Ch5_cmds)/sizeof(sfx_SFX_Battle_2F_Ch5_cmds[0])) },
    { 6, "SFX_Battle_2F_Ch6", sfx_SFX_Battle_2F_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2F_Ch6_cmds)/sizeof(sfx_SFX_Battle_2F_Ch6_cmds[0])) },
    { 8, "SFX_Battle_2F_Ch8", sfx_SFX_Battle_2F_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2F_Ch8_cmds)/sizeof(sfx_SFX_Battle_2F_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Psychic_M_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 15, 7, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1981 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1982 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1983 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1984 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 12, 4, 1985 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 2, 1984 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 0, 8, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Psychic_M_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1904 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1889 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1890 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 12, 4, 1891 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 12, 4, 1892 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 2, 1892 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Psychic_M_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 3, -7, 20 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 12, -7, 19 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 12, -7, 18 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 12, -7, 17 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 12, -7, 16 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 12, 2, 16 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_PSYCHIC_M_channels[] = {
    { 5, "SFX_Psychic_M_Ch5", sfx_SFX_Psychic_M_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Psychic_M_Ch5_cmds)/sizeof(sfx_SFX_Psychic_M_Ch5_cmds[0])) },
    { 6, "SFX_Psychic_M_Ch6", sfx_SFX_Psychic_M_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Psychic_M_Ch6_cmds)/sizeof(sfx_SFX_Psychic_M_Ch6_cmds[0])) },
    { 8, "SFX_Psychic_M_Ch8", sfx_SFX_Psychic_M_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Psychic_M_Ch8_cmds)/sizeof(sfx_SFX_Psychic_M_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_09_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 1, 0, 0, 0 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 9, 7, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 2, 1280 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 0, 8, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_09_channels[] = {
    { 5, "SFX_Battle_09_Ch5", sfx_SFX_Battle_09_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_09_Ch5_cmds)/sizeof(sfx_SFX_Battle_09_Ch5_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Faint_Fall_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 1, 0, 0, 0 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 10, -7, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 2, 1920 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 0, 8, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_FAINT_FALL_channels[] = {
    { 5, "SFX_Faint_Fall_Ch5", sfx_SFX_Faint_Fall_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Faint_Fall_Ch5_cmds)/sizeof(sfx_SFX_Faint_Fall_Ch5_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_33_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 15, 1, 1280 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 15, 1, 1408 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 15, 1, 1536 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 15, 1, 1664 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 15, 1, 1792 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_33_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 3, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 14, 1, 1296 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 14, 1, 1424 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 14, 1, 1552 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 6, 14, 1, 1680 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 14, 1, 1808 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_33_channels[] = {
    { 5, "SFX_Battle_33_Ch5", sfx_SFX_Battle_33_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_33_Ch5_cmds)/sizeof(sfx_SFX_Battle_33_Ch5_cmds[0])) },
    { 6, "SFX_Battle_33_Ch6", sfx_SFX_Battle_33_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_33_Ch6_cmds)/sizeof(sfx_SFX_Battle_33_Ch6_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_32_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 10, -7, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 15, 1, 1792 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 0, 8, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_32_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 3, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 15, 1, 1793 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_32_channels[] = {
    { 5, "SFX_Battle_32_Ch5", sfx_SFX_Battle_32_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_32_Ch5_cmds)/sizeof(sfx_SFX_Battle_32_Ch5_cmds[0])) },
    { 6, "SFX_Battle_32_Ch6", sfx_SFX_Battle_32_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_32_Ch6_cmds)/sizeof(sfx_SFX_Battle_32_Ch6_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_34_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 3, 2, 3, 1 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 15, -7, 1016 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, -7, 1024 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 3, 1024 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_34_Ch6_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 2, 3, 1, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 14, -7, 960 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 14, -7, 960 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 14, 3, 960 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_34_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 4, 15, -7, 81 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 15, -7, 84 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, -7, 85 },
    { MOVE_SFX_CMD_NOISE_NOTE, 15, 15, 3, 86 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_34_channels[] = {
    { 5, "SFX_Battle_34_Ch5", sfx_SFX_Battle_34_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_34_Ch5_cmds)/sizeof(sfx_SFX_Battle_34_Ch5_cmds[0])) },
    { 6, "SFX_Battle_34_Ch6", sfx_SFX_Battle_34_Ch6_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_34_Ch6_cmds)/sizeof(sfx_SFX_Battle_34_Ch6_cmds[0])) },
    { 8, "SFX_Battle_34_Ch8", sfx_SFX_Battle_34_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_34_Ch8_cmds)/sizeof(sfx_SFX_Battle_34_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2B_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE_PATTERN, 3, 1, 0, 2 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 8, 1, 768 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 12, 1, 1024 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 15, 1, 1280 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 11, 1, 1024 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 3, 7, 1, 768 },
    { MOVE_SFX_CMD_SOUND_LOOP, 5, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 8, 1, 1024 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_cmd_t sfx_SFX_Battle_2B_Ch8_cmds[] = {
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 6, 2, 34 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 10, 2, 50 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 13, 2, 51 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 9, 2, 35 },
    { MOVE_SFX_CMD_NOISE_NOTE, 3, 5, 2, 18 },
    { MOVE_SFX_CMD_SOUND_LOOP, 5, 0, 0, 0 },
    { MOVE_SFX_CMD_NOISE_NOTE, 8, 8, 1, 18 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_BATTLE_2B_channels[] = {
    { 5, "SFX_Battle_2B_Ch5", sfx_SFX_Battle_2B_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2B_Ch5_cmds)/sizeof(sfx_SFX_Battle_2B_Ch5_cmds[0])) },
    { 8, "SFX_Battle_2B_Ch8", sfx_SFX_Battle_2B_Ch8_cmds, (uint16_t)(sizeof(sfx_SFX_Battle_2B_Ch8_cmds)/sizeof(sfx_SFX_Battle_2B_Ch8_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Arrow_Tiles_1_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 0, 0, 0, 0 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 1, 7, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 13, 2, 1792 },
    { MOVE_SFX_CMD_PITCH_SWEEP, 0, 8, 0, 0 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_Arrow_Tiles_1_channels[] = {
    { 5, "SFX_Arrow_Tiles_1_Ch5", sfx_SFX_Arrow_Tiles_1_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Arrow_Tiles_1_Ch5_cmds)/sizeof(sfx_SFX_Arrow_Tiles_1_Ch5_cmds[0])) },
};

static const move_sfx_cmd_t sfx_SFX_Safari_Zone_PA_Ch5_cmds[] = {
    { MOVE_SFX_CMD_DUTY_CYCLE, 2, 0, 0, 0 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 3, 1840 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 8, 6, 5, 1840 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 15, 4, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 7, 4, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 4, 4, 1792 },
    { MOVE_SFX_CMD_SQUARE_NOTE, 15, 2, 4, 1792 },
    { MOVE_SFX_CMD_SOUND_RET, 0, 0, 0, 0 },
};

static const move_sfx_channel_def_t sfx_SFX_Safari_Zone_PA_channels[] = {
    { 5, "SFX_Safari_Zone_PA_Ch5", sfx_SFX_Safari_Zone_PA_Ch5_cmds, (uint16_t)(sizeof(sfx_SFX_Safari_Zone_PA_Ch5_cmds)/sizeof(sfx_SFX_Safari_Zone_PA_Ch5_cmds[0])) },
};

const move_sfx_def_t gMoveSfxStructs[] = {
    { "SFX_POUND", 2, sfx_SFX_POUND_channels, (uint8_t)(sizeof(sfx_SFX_POUND_channels)/sizeof(sfx_SFX_POUND_channels[0])) },
    { "SFX_BATTLE_0C", 2, sfx_SFX_BATTLE_0C_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_0C_channels)/sizeof(sfx_SFX_BATTLE_0C_channels[0])) },
    { "SFX_DOUBLESLAP", 2, sfx_SFX_DOUBLESLAP_channels, (uint8_t)(sizeof(sfx_SFX_DOUBLESLAP_channels)/sizeof(sfx_SFX_DOUBLESLAP_channels[0])) },
    { "SFX_BATTLE_0B", 2, sfx_SFX_BATTLE_0B_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_0B_channels)/sizeof(sfx_SFX_BATTLE_0B_channels[0])) },
    { "SFX_BATTLE_0D", 2, sfx_SFX_BATTLE_0D_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_0D_channels)/sizeof(sfx_SFX_BATTLE_0D_channels[0])) },
    { "SFX_SILPH_SCOPE", 2, sfx_SFX_SILPH_SCOPE_channels, (uint8_t)(sizeof(sfx_SFX_SILPH_SCOPE_channels)/sizeof(sfx_SFX_SILPH_SCOPE_channels[0])) },
    { "SFX_DAMAGE", 2, sfx_SFX_DAMAGE_channels, (uint8_t)(sizeof(sfx_SFX_DAMAGE_channels)/sizeof(sfx_SFX_DAMAGE_channels[0])) },
    { "SFX_BATTLE_0F", 2, sfx_SFX_BATTLE_0F_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_0F_channels)/sizeof(sfx_SFX_BATTLE_0F_channels[0])) },
    { "SFX_BATTLE_0E", 2, sfx_SFX_BATTLE_0E_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_0E_channels)/sizeof(sfx_SFX_BATTLE_0E_channels[0])) },
    { "SFX_NOT_VERY_EFFECTIVE", 2, sfx_SFX_NOT_VERY_EFFECTIVE_channels, (uint8_t)(sizeof(sfx_SFX_NOT_VERY_EFFECTIVE_channels)/sizeof(sfx_SFX_NOT_VERY_EFFECTIVE_channels[0])) },
    { "SFX_BATTLE_12", 2, sfx_SFX_BATTLE_12_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_12_channels)/sizeof(sfx_SFX_BATTLE_12_channels[0])) },
    { "SFX_BATTLE_13", 2, sfx_SFX_BATTLE_13_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_13_channels)/sizeof(sfx_SFX_BATTLE_13_channels[0])) },
    { "SFX_BATTLE_14", 2, sfx_SFX_BATTLE_14_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_14_channels)/sizeof(sfx_SFX_BATTLE_14_channels[0])) },
    { "SFX_BATTLE_22", 2, sfx_SFX_BATTLE_22_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_22_channels)/sizeof(sfx_SFX_BATTLE_22_channels[0])) },
    { "SFX_VINE_WHIP", 2, sfx_SFX_VINE_WHIP_channels, (uint8_t)(sizeof(sfx_SFX_VINE_WHIP_channels)/sizeof(sfx_SFX_VINE_WHIP_channels[0])) },
    { "SFX_BATTLE_20", 2, sfx_SFX_BATTLE_20_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_20_channels)/sizeof(sfx_SFX_BATTLE_20_channels[0])) },
    { "SFX_BATTLE_17", 2, sfx_SFX_BATTLE_17_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_17_channels)/sizeof(sfx_SFX_BATTLE_17_channels[0])) },
    { "SFX_SUPER_EFFECTIVE", 2, sfx_SFX_SUPER_EFFECTIVE_channels, (uint8_t)(sizeof(sfx_SFX_SUPER_EFFECTIVE_channels)/sizeof(sfx_SFX_SUPER_EFFECTIVE_channels[0])) },
    { "SFX_BATTLE_21", 2, sfx_SFX_BATTLE_21_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_21_channels)/sizeof(sfx_SFX_BATTLE_21_channels[0])) },
    { "SFX_BATTLE_1B", 2, sfx_SFX_BATTLE_1B_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_1B_channels)/sizeof(sfx_SFX_BATTLE_1B_channels[0])) },
    { "SFX_BATTLE_18", 2, sfx_SFX_BATTLE_18_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_18_channels)/sizeof(sfx_SFX_BATTLE_18_channels[0])) },
    { "SFX_BATTLE_1E", 2, sfx_SFX_BATTLE_1E_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_1E_channels)/sizeof(sfx_SFX_BATTLE_1E_channels[0])) },
    { "SFX_HORN_DRILL", 2, sfx_SFX_HORN_DRILL_channels, (uint8_t)(sizeof(sfx_SFX_HORN_DRILL_channels)/sizeof(sfx_SFX_HORN_DRILL_channels[0])) },
    { "SFX_BATTLE_19", 2, sfx_SFX_BATTLE_19_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_19_channels)/sizeof(sfx_SFX_BATTLE_19_channels[0])) },
    { "SFX_BATTLE_31", 2, sfx_SFX_BATTLE_31_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_31_channels)/sizeof(sfx_SFX_BATTLE_31_channels[0])) },
    { "SFX_BATTLE_35", 2, sfx_SFX_BATTLE_35_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_35_channels)/sizeof(sfx_SFX_BATTLE_35_channels[0])) },
    { "SFX_BATTLE_27", 2, sfx_SFX_BATTLE_27_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_27_channels)/sizeof(sfx_SFX_BATTLE_27_channels[0])) },
    { "SFX_BATTLE_2A", 2, sfx_SFX_BATTLE_2A_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_2A_channels)/sizeof(sfx_SFX_BATTLE_2A_channels[0])) },
    { "SFX_BATTLE_29", 2, sfx_SFX_BATTLE_29_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_29_channels)/sizeof(sfx_SFX_BATTLE_29_channels[0])) },
    { "SFX_BATTLE_24", 2, sfx_SFX_BATTLE_24_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_24_channels)/sizeof(sfx_SFX_BATTLE_24_channels[0])) },
    { "SFX_BATTLE_2C", 2, sfx_SFX_BATTLE_2C_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_2C_channels)/sizeof(sfx_SFX_BATTLE_2C_channels[0])) },
    { "SFX_BATTLE_28", 2, sfx_SFX_BATTLE_28_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_28_channels)/sizeof(sfx_SFX_BATTLE_28_channels[0])) },
    { "SFX_PSYBEAM", 2, sfx_SFX_PSYBEAM_channels, (uint8_t)(sizeof(sfx_SFX_PSYBEAM_channels)/sizeof(sfx_SFX_PSYBEAM_channels[0])) },
    { "SFX_BATTLE_36", 2, sfx_SFX_BATTLE_36_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_36_channels)/sizeof(sfx_SFX_BATTLE_36_channels[0])) },
    { "SFX_PECK", 2, sfx_SFX_PECK_channels, (uint8_t)(sizeof(sfx_SFX_PECK_channels)/sizeof(sfx_SFX_PECK_channels[0])) },
    { "SFX_BATTLE_23", 2, sfx_SFX_BATTLE_23_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_23_channels)/sizeof(sfx_SFX_BATTLE_23_channels[0])) },
    { "SFX_BATTLE_26", 2, sfx_SFX_BATTLE_26_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_26_channels)/sizeof(sfx_SFX_BATTLE_26_channels[0])) },
    { "SFX_BATTLE_25", 2, sfx_SFX_BATTLE_25_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_25_channels)/sizeof(sfx_SFX_BATTLE_25_channels[0])) },
    { "SFX_BATTLE_2E", 2, sfx_SFX_BATTLE_2E_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_2E_channels)/sizeof(sfx_SFX_BATTLE_2E_channels[0])) },
    { "SFX_BATTLE_1C", 2, sfx_SFX_BATTLE_1C_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_1C_channels)/sizeof(sfx_SFX_BATTLE_1C_channels[0])) },
    { "SFX_BATTLE_2F", 2, sfx_SFX_BATTLE_2F_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_2F_channels)/sizeof(sfx_SFX_BATTLE_2F_channels[0])) },
    { "SFX_PSYCHIC_M", 2, sfx_SFX_PSYCHIC_M_channels, (uint8_t)(sizeof(sfx_SFX_PSYCHIC_M_channels)/sizeof(sfx_SFX_PSYCHIC_M_channels[0])) },
    { "SFX_BATTLE_09", 2, sfx_SFX_BATTLE_09_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_09_channels)/sizeof(sfx_SFX_BATTLE_09_channels[0])) },
    { "SFX_FAINT_FALL", 2, sfx_SFX_FAINT_FALL_channels, (uint8_t)(sizeof(sfx_SFX_FAINT_FALL_channels)/sizeof(sfx_SFX_FAINT_FALL_channels[0])) },
    { "SFX_BATTLE_33", 2, sfx_SFX_BATTLE_33_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_33_channels)/sizeof(sfx_SFX_BATTLE_33_channels[0])) },
    { "SFX_BATTLE_32", 2, sfx_SFX_BATTLE_32_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_32_channels)/sizeof(sfx_SFX_BATTLE_32_channels[0])) },
    { "SFX_BATTLE_34", 2, sfx_SFX_BATTLE_34_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_34_channels)/sizeof(sfx_SFX_BATTLE_34_channels[0])) },
    { "SFX_BATTLE_2B", 2, sfx_SFX_BATTLE_2B_channels, (uint8_t)(sizeof(sfx_SFX_BATTLE_2B_channels)/sizeof(sfx_SFX_BATTLE_2B_channels[0])) },
    { "SFX_Arrow_Tiles_1", 1, sfx_SFX_Arrow_Tiles_1_channels, (uint8_t)(sizeof(sfx_SFX_Arrow_Tiles_1_channels)/sizeof(sfx_SFX_Arrow_Tiles_1_channels[0])) },
    { "SFX_Safari_Zone_PA", 1, sfx_SFX_Safari_Zone_PA_channels, (uint8_t)(sizeof(sfx_SFX_Safari_Zone_PA_channels)/sizeof(sfx_SFX_Safari_Zone_PA_channels[0])) },
};
const uint16_t gMoveSfxStructCount = (uint16_t)(sizeof(gMoveSfxStructs)/sizeof(gMoveSfxStructs[0]));
