#pragma once
/* party_icon_data.h -- Generated by tools/extract_party_icons.py */
#include <stdint.h>

/* Icon type constants (mirror of pokered constants/icon_constants.asm) */
#define ICON_MON         0
#define ICON_BALL        1
#define ICON_HELIX       2
#define ICON_FAIRY       3
#define ICON_BIRD        4
#define ICON_WATER       5
#define ICON_BUG         6
#define ICON_GRASS       7
#define ICON_SNAKE       8
#define ICON_QUADRUPED   9
#define ICON_TRADEBUBBLE 14
#define ICON_ICONOFFSET  64   /* $40: frame2 tile slot = ICONOFFSET + ICON_TYPE<<2 */

/* dex index 1-151 -> ICON_* type (index 0 unused) */
extern const uint8_t gMonPartyIconType[152];

/* Sprite tile data indexed by sprite_tile_gfx slot. */
extern const uint8_t gIconTileGfx[256][16];

/* Load party icon tile data into sprite_tile_gfx. */
void PartyIcons_LoadTiles(void);
