#pragma once
/* splash_screen_data.h -- AUTO-GENERATED by tools/extract_splash_screen.py. */
#include <stdint.h>

#define SPLASH_GAMEFREAK_LOGO_TILES      6
#define SPLASH_FALLING_STAR_TILES        1
#define SPLASH_SHOOTING_STAR_TILES       2
#define SPLASH_GAMEFREAK_PRESENTS_TILES 13
#define SPLASH_LEGAL_TILES              28

extern const uint8_t gSplashGameFreakLogoTiles[SPLASH_GAMEFREAK_LOGO_TILES][16];
extern const uint8_t gSplashFallingStarTiles[SPLASH_FALLING_STAR_TILES][16];
extern const uint8_t gSplashShootingStarTiles[SPLASH_SHOOTING_STAR_TILES][16];
extern const uint8_t gSplashGameFreakPresentsTiles[SPLASH_GAMEFREAK_PRESENTS_TILES][16];
extern const uint8_t gSplashLegalTiles[SPLASH_LEGAL_TILES][16];
