#pragma once
/* title_screen_data.h -- AUTO-GENERATED by tools/extract_title_screen.py. */
#include <stdint.h>

#define TITLE_LOGO_TILES        112
#define TITLE_RED_VERSION_TILES   10
#define TITLE_PLAYER_TILES       35
#define TITLE_COPYRIGHT_TILES    14

extern const uint8_t gTitleLogoTiles[TITLE_LOGO_TILES][16];
extern const uint8_t gTitleRedVersionTiles[TITLE_RED_VERSION_TILES][16];
extern const uint8_t gTitlePlayerTiles[TITLE_PLAYER_TILES][16];
extern const uint8_t gTitleCopyrightTiles[TITLE_COPYRIGHT_TILES][16];
