#pragma once

#include <stdint.h>

/* Generated by tools/extract_town_map.py from pokered-master/gfx/town_map assets. */

#define TOWN_MAP_WORLD_TILE_BASE 0x60
#define TOWN_MAP_WORLD_TILE_COUNT 16
#define TOWN_MAP_FIRST_INDOOR_MAP 0x25
#define TOWN_MAP_SCREEN_TILE_COUNT (20 * 18)

extern const uint8_t gTownMapWorldTiles[TOWN_MAP_WORLD_TILE_COUNT][16];
extern const uint8_t gTownMapCursorTiles[4][16];
extern const uint8_t gTownMapCompressedMap[];
extern const uint8_t gTownMapExternalCoords[TOWN_MAP_FIRST_INDOOR_MAP];
extern const uint8_t gTownMapOrderMapIds[];
extern const int gTownMapOrderCount;

typedef struct {
    uint8_t group_end;
    uint8_t coords;
} town_map_internal_entry_t;
extern const town_map_internal_entry_t gTownMapInternalCoords[];
extern const int gTownMapInternalCoordsCount;

void TownMapData_LoadTiles(void);
