/* trainer_data.c — Generated trainer party data.
 *
 * Source of truth:
 *   - pokered-master/data/trainers/parties.asm
 *   - pokered-master/data/trainers/pic_pointers_money.asm
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: python tools/extract_trainers.py
 */
#include "trainer_data.h"
#include "game/constants.h"

/* ---- Youngster (class 1) ------------------------------------------ */
static const uint8_t gYoungsterParties[] = {
    /* Route 3 */
    11, SPECIES_RATTATA, SPECIES_EKANS, 0,
    14, SPECIES_SPEAROW, 0,
    /* Mt. Moon 1F */
    10, SPECIES_RATTATA, SPECIES_RATTATA, SPECIES_ZUBAT, 0,
    /* Route 24 */
    14, SPECIES_RATTATA, SPECIES_EKANS, SPECIES_ZUBAT, 0,
    /* Route 25 */
    15, SPECIES_RATTATA, SPECIES_SPEAROW, 0,
    17, SPECIES_SLOWPOKE, 0,
    14, SPECIES_EKANS, SPECIES_SANDSHREW, 0,
    /* SS Anne 1F Rooms */
    21, SPECIES_NIDORAN_M, 0,
    /* Route 11 */
    21, SPECIES_EKANS, 0,
    19, SPECIES_SANDSHREW, SPECIES_ZUBAT, 0,
    17, SPECIES_RATTATA, SPECIES_RATTATA, SPECIES_RATICATE, 0,
    18, SPECIES_NIDORAN_M, SPECIES_NIDORINO, 0,
    /* Unused */
    17, SPECIES_SPEAROW, SPECIES_RATTATA, SPECIES_RATTATA, SPECIES_SPEAROW, 0,
};

/* ---- BugCatcher (class 2) ------------------------------------------ */
static const uint8_t gBugCatcherParties[] = {
    /* Viridian Forest */
    6, SPECIES_WEEDLE, SPECIES_CATERPIE, 0,
    7, SPECIES_WEEDLE, SPECIES_KAKUNA, SPECIES_WEEDLE, 0,
    9, SPECIES_WEEDLE, 0,
    /* Route 3 */
    10, SPECIES_CATERPIE, SPECIES_WEEDLE, SPECIES_CATERPIE, 0,
    9, SPECIES_WEEDLE, SPECIES_KAKUNA, SPECIES_CATERPIE, SPECIES_METAPOD, 0,
    11, SPECIES_CATERPIE, SPECIES_METAPOD, 0,
    /* Mt. Moon 1F */
    11, SPECIES_WEEDLE, SPECIES_KAKUNA, 0,
    10, SPECIES_CATERPIE, SPECIES_METAPOD, SPECIES_CATERPIE, 0,
    /* Route 24 */
    14, SPECIES_CATERPIE, SPECIES_WEEDLE, 0,
    /* Route 6 */
    16, SPECIES_WEEDLE, SPECIES_CATERPIE, SPECIES_WEEDLE, 0,
    20, SPECIES_BUTTERFREE, 0,
    /* Unused */
    18, SPECIES_METAPOD, SPECIES_CATERPIE, SPECIES_VENONAT, 0,
    /* Route 9 */
    19, SPECIES_BEEDRILL, SPECIES_BEEDRILL, 0,
    20, SPECIES_CATERPIE, SPECIES_WEEDLE, SPECIES_VENONAT, 0,
};

/* ---- Lass (class 3) ------------------------------------------ */
static const uint8_t gLassParties[] = {
    /* Route 3 */
    9, SPECIES_PIDGEY, SPECIES_PIDGEY, 0,
    10, SPECIES_RATTATA, SPECIES_NIDORAN_M, 0,
    14, SPECIES_JIGGLYPUFF, 0,
    /* Route 4 */
    31, SPECIES_PARAS, SPECIES_PARAS, SPECIES_PARASECT, 0,
    /* Mt. Moon 1F */
    11, SPECIES_ODDISH, SPECIES_BELLSPROUT, 0,
    14, SPECIES_CLEFAIRY, 0,
    /* Route 24 */
    16, SPECIES_PIDGEY, SPECIES_NIDORAN_F, 0,
    14, SPECIES_PIDGEY, SPECIES_NIDORAN_F, 0,
    /* Route 25 */
    15, SPECIES_NIDORAN_M, SPECIES_NIDORAN_F, 0,
    13, SPECIES_ODDISH, SPECIES_PIDGEY, SPECIES_ODDISH, 0,
    /* SS Anne 1F Rooms */
    18, SPECIES_PIDGEY, SPECIES_NIDORAN_F, 0,
    /* SS Anne 2F Rooms */
    18, SPECIES_RATTATA, SPECIES_PIKACHU, 0,
    /* Route 8 */
    23, SPECIES_NIDORAN_F, SPECIES_NIDORINA, 0,
    24, SPECIES_MEOWTH, SPECIES_MEOWTH, SPECIES_MEOWTH, 0,
    19, SPECIES_PIDGEY, SPECIES_RATTATA, SPECIES_NIDORAN_M, SPECIES_MEOWTH, SPECIES_PIKACHU, 0,
    22, SPECIES_CLEFAIRY, SPECIES_CLEFAIRY, 0,
    /* Celadon Gym */
    23, SPECIES_BELLSPROUT, SPECIES_WEEPINBELL, 0,
    23, SPECIES_ODDISH, SPECIES_GLOOM, 0,
};

/* ---- Sailor (class 4) ------------------------------------------ */
static const uint8_t gSailorParties[] = {
    /* SS Anne Stern */
    18, SPECIES_MACHOP, SPECIES_SHELLDER, 0,
    17, SPECIES_MACHOP, SPECIES_TENTACOOL, 0,
    /* SS Anne B1F Rooms */
    21, SPECIES_SHELLDER, 0,
    17, SPECIES_HORSEA, SPECIES_SHELLDER, SPECIES_TENTACOOL, 0,
    18, SPECIES_TENTACOOL, SPECIES_STARYU, 0,
    17, SPECIES_HORSEA, SPECIES_HORSEA, SPECIES_HORSEA, 0,
    20, SPECIES_MACHOP, 0,
    /* Vermilion Gym */
    21, SPECIES_PIKACHU, SPECIES_PIKACHU, 0,
};

/* ---- JrTrainerM (class 5) ------------------------------------------ */
static const uint8_t gJrTrainerMParties[] = {
    /* Pewter Gym */
    11, SPECIES_DIGLETT, SPECIES_SANDSHREW, 0,
    /* Route 24/Route 25 */
    14, SPECIES_RATTATA, SPECIES_EKANS, 0,
    /* Route 24 */
    18, SPECIES_MANKEY, 0,
    /* Route 6 */
    20, SPECIES_SQUIRTLE, 0,
    16, SPECIES_SPEAROW, SPECIES_RATICATE, 0,
    /* Unused */
    18, SPECIES_DIGLETT, SPECIES_DIGLETT, SPECIES_SANDSHREW, 0,
    /* Route 9 */
    21, SPECIES_GROWLITHE, SPECIES_CHARMANDER, 0,
    19, SPECIES_RATTATA, SPECIES_DIGLETT, SPECIES_EKANS, SPECIES_SANDSHREW, 0,
    /* Route 12 */
    29, SPECIES_NIDORAN_M, SPECIES_NIDORINO, 0,
};

/* ---- JrTrainerF (class 6) ------------------------------------------ */
static const uint8_t gJrTrainerFParties[] = {
    /* Cerulean Gym */
    19, SPECIES_GOLDEEN, 0,
    /* Route 6 */
    16, SPECIES_RATTATA, SPECIES_PIKACHU, 0,
    16, SPECIES_PIDGEY, SPECIES_PIDGEY, SPECIES_PIDGEY, 0,
    /* Unused */
    22, SPECIES_BULBASAUR, 0,
    /* Route 9 */
    18, SPECIES_ODDISH, SPECIES_BELLSPROUT, SPECIES_ODDISH, SPECIES_BELLSPROUT, 0,
    23, SPECIES_MEOWTH, 0,
    /* Route 10 */
    20, SPECIES_PIKACHU, SPECIES_CLEFAIRY, 0,
    21, SPECIES_PIDGEY, SPECIES_PIDGEOTTO, 0,
    /* Rock Tunnel B1F */
    21, SPECIES_JIGGLYPUFF, SPECIES_PIDGEY, SPECIES_MEOWTH, 0,
    22, SPECIES_ODDISH, SPECIES_BULBASAUR, 0,
    /* Celadon Gym */
    24, SPECIES_BULBASAUR, SPECIES_IVYSAUR, 0,
    /* Route 13 */
    24, SPECIES_PIDGEY, SPECIES_MEOWTH, SPECIES_RATTATA, SPECIES_PIKACHU, SPECIES_MEOWTH, 0,
    30, SPECIES_POLIWAG, SPECIES_POLIWAG, 0,
    27, SPECIES_PIDGEY, SPECIES_MEOWTH, SPECIES_PIDGEY, SPECIES_PIDGEOTTO, 0,
    28, SPECIES_GOLDEEN, SPECIES_POLIWAG, SPECIES_HORSEA, 0,
    /* Route 20 */
    31, SPECIES_GOLDEEN, SPECIES_SEAKING, 0,
    /* Rock Tunnel 1F */
    22, SPECIES_BELLSPROUT, SPECIES_CLEFAIRY, 0,
    20, SPECIES_MEOWTH, SPECIES_ODDISH, SPECIES_PIDGEY, 0,
    19, SPECIES_PIDGEY, SPECIES_RATTATA, SPECIES_RATTATA, SPECIES_BELLSPROUT, 0,
    /* Route 15 */
    28, SPECIES_GLOOM, SPECIES_ODDISH, SPECIES_ODDISH, 0,
    29, SPECIES_PIKACHU, SPECIES_RAICHU, 0,
    33, SPECIES_CLEFAIRY, 0,
    29, SPECIES_BELLSPROUT, SPECIES_ODDISH, SPECIES_TANGELA, 0,
    /* Route 20 */
    30, SPECIES_TENTACOOL, SPECIES_HORSEA, SPECIES_SEEL, 0,
};

/* ---- Pokemaniac (class 7) ------------------------------------------ */
static const uint8_t gPokemaniacParties[] = {
    /* Route 10 */
    30, SPECIES_RHYHORN, SPECIES_LICKITUNG, 0,
    20, SPECIES_CUBONE, SPECIES_SLOWPOKE, 0,
    /* Rock Tunnel B1F */
    20, SPECIES_SLOWPOKE, SPECIES_SLOWPOKE, SPECIES_SLOWPOKE, 0,
    22, SPECIES_CHARMANDER, SPECIES_CUBONE, 0,
    25, SPECIES_SLOWPOKE, 0,
    /* Victory Road 2F */
    40, SPECIES_CHARMELEON, SPECIES_LAPRAS, SPECIES_LICKITUNG, 0,
    /* Rock Tunnel 1F */
    23, SPECIES_CUBONE, SPECIES_SLOWPOKE, 0,
};

/* ---- SuperNerd (class 8) ------------------------------------------ */
static const uint8_t gSuperNerdParties[] = {
    /* Mt. Moon 1F */
    11, SPECIES_MAGNEMITE, SPECIES_VOLTORB, 0,
    /* Mt. Moon B2F */
    12, SPECIES_GRIMER, SPECIES_VOLTORB, SPECIES_KOFFING, 0,
    /* Route 8 */
    20, SPECIES_VOLTORB, SPECIES_KOFFING, SPECIES_VOLTORB, SPECIES_MAGNEMITE, 0,
    22, SPECIES_GRIMER, SPECIES_MUK, SPECIES_GRIMER, 0,
    26, SPECIES_KOFFING, 0,
    /* Unused */
    22, SPECIES_KOFFING, SPECIES_MAGNEMITE, SPECIES_WEEZING, 0,
    20, SPECIES_MAGNEMITE, SPECIES_MAGNEMITE, SPECIES_KOFFING, SPECIES_MAGNEMITE, 0,
    24, SPECIES_MAGNEMITE, SPECIES_VOLTORB, 0,
    /* Cinnabar Gym */
    36, SPECIES_VULPIX, SPECIES_VULPIX, SPECIES_NINETALES, 0,
    34, SPECIES_PONYTA, SPECIES_CHARMANDER, SPECIES_VULPIX, SPECIES_GROWLITHE, 0,
    41, SPECIES_RAPIDASH, 0,
    37, SPECIES_GROWLITHE, SPECIES_VULPIX, 0,
};

/* ---- Hiker (class 9) ------------------------------------------ */
static const uint8_t gHikerParties[] = {
    /* Mt. Moon 1F */
    10, SPECIES_GEODUDE, SPECIES_GEODUDE, SPECIES_ONIX, 0,
    /* Route 25 */
    15, SPECIES_MACHOP, SPECIES_GEODUDE, 0,
    13, SPECIES_GEODUDE, SPECIES_GEODUDE, SPECIES_MACHOP, SPECIES_GEODUDE, 0,
    17, SPECIES_ONIX, 0,
    /* Route 9 */
    21, SPECIES_GEODUDE, SPECIES_ONIX, 0,
    20, SPECIES_GEODUDE, SPECIES_MACHOP, SPECIES_GEODUDE, 0,
    /* Route 10 */
    21, SPECIES_GEODUDE, SPECIES_ONIX, 0,
    19, SPECIES_ONIX, SPECIES_GRAVELER, 0,
    /* Rock Tunnel B1F */
    21, SPECIES_GEODUDE, SPECIES_GEODUDE, SPECIES_GRAVELER, 0,
    25, SPECIES_GEODUDE, 0,
    /* Route 9/Rock Tunnel B1F */
    20, SPECIES_MACHOP, SPECIES_ONIX, 0,
    /* Rock Tunnel 1F */
    19, SPECIES_GEODUDE, SPECIES_MACHOP, SPECIES_GEODUDE, SPECIES_GEODUDE, 0,
    20, SPECIES_ONIX, SPECIES_ONIX, SPECIES_GEODUDE, 0,
    21, SPECIES_GEODUDE, SPECIES_GRAVELER, 0,
};

/* ---- Biker (class 10) ------------------------------------------ */
static const uint8_t gBikerParties[] = {
    /* Route 13 */
    28, SPECIES_KOFFING, SPECIES_KOFFING, SPECIES_KOFFING, 0,
    /* Route 14 */
    29, SPECIES_KOFFING, SPECIES_GRIMER, 0,
    /* Route 15 */
    25, SPECIES_KOFFING, SPECIES_KOFFING, SPECIES_WEEZING, SPECIES_KOFFING, SPECIES_GRIMER, 0,
    28, SPECIES_KOFFING, SPECIES_GRIMER, SPECIES_WEEZING, 0,
    /* Route 16 */
    29, SPECIES_GRIMER, SPECIES_KOFFING, 0,
    33, SPECIES_WEEZING, 0,
    26, SPECIES_GRIMER, SPECIES_GRIMER, SPECIES_GRIMER, SPECIES_GRIMER, 0,
    /* for MissingNo: 0, 33, MUK, 0, 29, VOLTORB, VOLTORB, 0, ..., 28, GRIMER, GRIMER. */
    28, SPECIES_WEEZING, SPECIES_KOFFING, SPECIES_WEEZING, 0,
    33, SPECIES_MUK, 0,
    29, SPECIES_VOLTORB, SPECIES_VOLTORB, 0,
    29, SPECIES_WEEZING, SPECIES_MUK, 0,
    25, SPECIES_KOFFING, SPECIES_WEEZING, SPECIES_KOFFING, SPECIES_KOFFING, SPECIES_WEEZING, 0,
    /* Route 14 */
    26, SPECIES_KOFFING, SPECIES_KOFFING, SPECIES_GRIMER, SPECIES_KOFFING, 0,
    28, SPECIES_GRIMER, SPECIES_GRIMER, SPECIES_KOFFING, 0,
    29, SPECIES_KOFFING, SPECIES_MUK, 0,
};

/* ---- Burglar (class 11) ------------------------------------------ */
static const uint8_t gBurglarParties[] = {
    /* Unused */
    29, SPECIES_GROWLITHE, SPECIES_VULPIX, 0,
    33, SPECIES_GROWLITHE, 0,
    28, SPECIES_VULPIX, SPECIES_CHARMANDER, SPECIES_PONYTA, 0,
    /* Cinnabar Gym */
    36, SPECIES_GROWLITHE, SPECIES_VULPIX, SPECIES_NINETALES, 0,
    41, SPECIES_PONYTA, 0,
    37, SPECIES_VULPIX, SPECIES_GROWLITHE, 0,
    /* Mansion 2F */
    34, SPECIES_CHARMANDER, SPECIES_CHARMELEON, 0,
    /* Mansion 3F */
    38, SPECIES_NINETALES, 0,
    /* Mansion B1F */
    34, SPECIES_GROWLITHE, SPECIES_PONYTA, 0,
};

/* ---- Engineer (class 12) ------------------------------------------ */
static const uint8_t gEngineerParties[] = {
    /* Unused */
    21, SPECIES_VOLTORB, SPECIES_MAGNEMITE, 0,
    /* Route 11 */
    21, SPECIES_MAGNEMITE, 0,
    18, SPECIES_MAGNEMITE, SPECIES_MAGNEMITE, SPECIES_MAGNETON, 0,
};

/* ---- UnusedJuggler (class 13) ------------------------------------------ */
static const uint8_t gUnusedJugglerParties[] = {
    0,
};

/* ---- Fisher (class 14) ------------------------------------------ */
static const uint8_t gFisherParties[] = {
    /* SS Anne 2F Rooms */
    17, SPECIES_GOLDEEN, SPECIES_TENTACOOL, SPECIES_GOLDEEN, 0,
    /* SS Anne B1F Rooms */
    17, SPECIES_TENTACOOL, SPECIES_STARYU, SPECIES_SHELLDER, 0,
    /* Route 12 */
    22, SPECIES_GOLDEEN, SPECIES_POLIWAG, SPECIES_GOLDEEN, 0,
    24, SPECIES_TENTACOOL, SPECIES_GOLDEEN, 0,
    27, SPECIES_GOLDEEN, 0,
    21, SPECIES_POLIWAG, SPECIES_SHELLDER, SPECIES_GOLDEEN, SPECIES_HORSEA, 0,
    /* Route 21 */
    28, SPECIES_SEAKING, SPECIES_GOLDEEN, SPECIES_SEAKING, SPECIES_SEAKING, 0,
    31, SPECIES_SHELLDER, SPECIES_CLOYSTER, 0,
    27, SPECIES_MAGIKARP, SPECIES_MAGIKARP, SPECIES_MAGIKARP, SPECIES_MAGIKARP,
    SPECIES_MAGIKARP, SPECIES_MAGIKARP, 0,
    33, SPECIES_SEAKING, SPECIES_GOLDEEN, 0,
    /* Route 12 */
    24, SPECIES_MAGIKARP, SPECIES_MAGIKARP, 0,
};

/* ---- Swimmer (class 15) ------------------------------------------ */
static const uint8_t gSwimmerParties[] = {
    /* Cerulean Gym */
    16, SPECIES_HORSEA, SPECIES_SHELLDER, 0,
    /* Route 19 */
    30, SPECIES_TENTACOOL, SPECIES_SHELLDER, 0,
    29, SPECIES_GOLDEEN, SPECIES_HORSEA, SPECIES_STARYU, 0,
    30, SPECIES_POLIWAG, SPECIES_POLIWHIRL, 0,
    27, SPECIES_HORSEA, SPECIES_TENTACOOL, SPECIES_TENTACOOL, SPECIES_GOLDEEN, 0,
    29, SPECIES_GOLDEEN, SPECIES_SHELLDER, SPECIES_SEAKING, 0,
    30, SPECIES_HORSEA, SPECIES_HORSEA, 0,
    27, SPECIES_TENTACOOL, SPECIES_TENTACOOL, SPECIES_STARYU, SPECIES_HORSEA,
    SPECIES_TENTACRUEL, 0,
    /* Route 20 */
    31, SPECIES_SHELLDER, SPECIES_CLOYSTER, 0,
    35, SPECIES_STARYU, 0,
    28, SPECIES_HORSEA, SPECIES_HORSEA, SPECIES_SEADRA, SPECIES_HORSEA, 0,
    /* Route 21 */
    33, SPECIES_SEADRA, SPECIES_TENTACRUEL, 0,
    37, SPECIES_STARMIE, 0,
    33, SPECIES_STARYU, SPECIES_WARTORTLE, 0,
    32, SPECIES_POLIWHIRL, SPECIES_TENTACOOL, SPECIES_SEADRA, 0,
};

/* ---- CueBall (class 16) ------------------------------------------ */
static const uint8_t gCueBallParties[] = {
    /* Route 16 */
    28, SPECIES_MACHOP, SPECIES_MANKEY, SPECIES_MACHOP, 0,
    29, SPECIES_MANKEY, SPECIES_MACHOP, 0,
    33, SPECIES_MACHOP, 0,
    /* Route 17 */
    29, SPECIES_MANKEY, SPECIES_PRIMEAPE, 0,
    29, SPECIES_MACHOP, SPECIES_MACHOKE, 0,
    33, SPECIES_MACHOKE, 0,
    26, SPECIES_MANKEY, SPECIES_MANKEY, SPECIES_MACHOKE, SPECIES_MACHOP, 0,
    29, SPECIES_PRIMEAPE, SPECIES_MACHOKE, 0,
    /* Route 21 */
    31, SPECIES_TENTACOOL, SPECIES_TENTACOOL, SPECIES_TENTACRUEL, 0,
};

/* ---- Gambler (class 17) ------------------------------------------ */
static const uint8_t gGamblerParties[] = {
    /* Route 11 */
    18, SPECIES_POLIWAG, SPECIES_HORSEA, 0,
    18, SPECIES_BELLSPROUT, SPECIES_ODDISH, 0,
    18, SPECIES_VOLTORB, SPECIES_MAGNEMITE, 0,
    18, SPECIES_GROWLITHE, SPECIES_VULPIX, 0,
    /* Route 8 */
    22, SPECIES_POLIWAG, SPECIES_POLIWAG, SPECIES_POLIWHIRL, 0,
    /* Unused */
    22, SPECIES_ONIX, SPECIES_GEODUDE, SPECIES_GRAVELER, 0,
    /* Route 8 */
    24, SPECIES_GROWLITHE, SPECIES_VULPIX, 0,
};

/* ---- Beauty (class 18) ------------------------------------------ */
static const uint8_t gBeautyParties[] = {
    /* Celadon Gym */
    21, SPECIES_ODDISH, SPECIES_BELLSPROUT, SPECIES_ODDISH, SPECIES_BELLSPROUT, 0,
    24, SPECIES_BELLSPROUT, SPECIES_BELLSPROUT, 0,
    26, SPECIES_EXEGGCUTE, 0,
    /* Route 13 */
    27, SPECIES_RATTATA, SPECIES_PIKACHU, SPECIES_RATTATA, 0,
    29, SPECIES_CLEFAIRY, SPECIES_MEOWTH, 0,
    /* Route 20 */
    35, SPECIES_SEAKING, 0,
    30, SPECIES_SHELLDER, SPECIES_SHELLDER, SPECIES_CLOYSTER, 0,
    31, SPECIES_POLIWAG, SPECIES_SEAKING, 0,
    /* Route 15 */
    29, SPECIES_PIDGEOTTO, SPECIES_WIGGLYTUFF, 0,
    29, SPECIES_BULBASAUR, SPECIES_IVYSAUR, 0,
    /* Unused */
    33, SPECIES_WEEPINBELL, SPECIES_BELLSPROUT, SPECIES_WEEPINBELL, 0,
    /* Route 19 */
    27, SPECIES_POLIWAG, SPECIES_GOLDEEN, SPECIES_SEAKING, SPECIES_GOLDEEN, SPECIES_POLIWAG, 0,
    30, SPECIES_GOLDEEN, SPECIES_SEAKING, 0,
    29, SPECIES_STARYU, SPECIES_STARYU, SPECIES_STARYU, 0,
    /* Route 20 */
    30, SPECIES_SEADRA, SPECIES_HORSEA, SPECIES_SEADRA, 0,
};

/* ---- Psychic (class 19) ------------------------------------------ */
static const uint8_t gPsychicParties[] = {
    /* Saffron Gym */
    31, SPECIES_KADABRA, SPECIES_SLOWPOKE, SPECIES_MR_MIME, SPECIES_KADABRA, 0,
    34, SPECIES_MR_MIME, SPECIES_KADABRA, 0,
    33, SPECIES_SLOWPOKE, SPECIES_SLOWPOKE, SPECIES_SLOWBRO, 0,
    38, SPECIES_SLOWBRO, 0,
};

/* ---- Rocker (class 20) ------------------------------------------ */
static const uint8_t gRockerParties[] = {
    /* Vermilion Gym */
    20, SPECIES_VOLTORB, SPECIES_MAGNEMITE, SPECIES_VOLTORB, 0,
    /* Route 12 */
    29, SPECIES_VOLTORB, SPECIES_ELECTRODE, 0,
};

/* ---- Juggler (class 21) ------------------------------------------ */
static const uint8_t gJugglerParties[] = {
    /* Silph Co. 5F */
    29, SPECIES_KADABRA, SPECIES_MR_MIME, 0,
    /* Victory Road 2F */
    41, SPECIES_DROWZEE, SPECIES_HYPNO, SPECIES_KADABRA, SPECIES_KADABRA, 0,
    /* Fuchsia Gym */
    31, SPECIES_DROWZEE, SPECIES_DROWZEE, SPECIES_KADABRA, SPECIES_DROWZEE, 0,
    34, SPECIES_DROWZEE, SPECIES_HYPNO, 0,
    /* Victory Road 2F */
    48, SPECIES_MR_MIME, 0,
    /* Unused */
    33, SPECIES_HYPNO, 0,
    /* Fuchsia Gym */
    38, SPECIES_HYPNO, 0,
    34, SPECIES_DROWZEE, SPECIES_KADABRA, 0,
};

/* ---- Tamer (class 22) ------------------------------------------ */
static const uint8_t gTamerParties[] = {
    /* Fuchsia Gym */
    34, SPECIES_SANDSLASH, SPECIES_ARBOK, 0,
    33, SPECIES_ARBOK, SPECIES_SANDSLASH, SPECIES_ARBOK, 0,
    /* Viridian Gym */
    43, SPECIES_RHYHORN, 0,
    39, SPECIES_ARBOK, SPECIES_TAUROS, 0,
    /* Victory Road 2F */
    44, SPECIES_PERSIAN, SPECIES_GOLDUCK, 0,
    /* Unused */
    42, SPECIES_RHYHORN, SPECIES_PRIMEAPE, SPECIES_ARBOK, SPECIES_TAUROS, 0,
};

/* ---- BirdKeeper (class 23) ------------------------------------------ */
static const uint8_t gBirdKeeperParties[] = {
    /* Route 13 */
    29, SPECIES_PIDGEY, SPECIES_PIDGEOTTO, 0,
    25, SPECIES_SPEAROW, SPECIES_PIDGEY, SPECIES_PIDGEY, SPECIES_SPEAROW, SPECIES_SPEAROW, 0,
    26, SPECIES_PIDGEY, SPECIES_PIDGEOTTO, SPECIES_SPEAROW, SPECIES_FEAROW, 0,
    /* Route 14 */
    33, SPECIES_FARFETCHD, 0,
    29, SPECIES_SPEAROW, SPECIES_FEAROW, 0,
    /* Route 15 */
    26, SPECIES_PIDGEOTTO, SPECIES_FARFETCHD, SPECIES_DODUO, SPECIES_PIDGEY, 0,
    28, SPECIES_DODRIO, SPECIES_DODUO, SPECIES_DODUO, 0,
    /* Route 18 */
    29, SPECIES_SPEAROW, SPECIES_FEAROW, 0,
    34, SPECIES_DODRIO, 0,
    26, SPECIES_SPEAROW, SPECIES_SPEAROW, SPECIES_FEAROW, SPECIES_SPEAROW, 0,
    /* Route 20 */
    30, SPECIES_FEAROW, SPECIES_FEAROW, SPECIES_PIDGEOTTO, 0,
    /* Unused */
    39, SPECIES_PIDGEOTTO, SPECIES_PIDGEOTTO, SPECIES_PIDGEY, SPECIES_PIDGEOTTO, 0,
    42, SPECIES_FARFETCHD, SPECIES_FEAROW, 0,
    /* Route 14 */
    28, SPECIES_PIDGEY, SPECIES_DODUO, SPECIES_PIDGEOTTO, 0,
    26, SPECIES_PIDGEY, SPECIES_SPEAROW, SPECIES_PIDGEY, SPECIES_FEAROW, 0,
    29, SPECIES_PIDGEOTTO, SPECIES_FEAROW, 0,
    28, SPECIES_SPEAROW, SPECIES_DODUO, SPECIES_FEAROW, 0,
};

/* ---- Blackbelt (class 24) ------------------------------------------ */
static const uint8_t gBlackbeltParties[] = {
    /* Fighting Dojo */
    37, SPECIES_HITMONLEE, SPECIES_HITMONCHAN, 0,
    31, SPECIES_MANKEY, SPECIES_MANKEY, SPECIES_PRIMEAPE, 0,
    32, SPECIES_MACHOP, SPECIES_MACHOKE, 0,
    36, SPECIES_PRIMEAPE, 0,
    31, SPECIES_MACHOP, SPECIES_MANKEY, SPECIES_PRIMEAPE, 0,
    /* Viridian Gym */
    40, SPECIES_MACHOP, SPECIES_MACHOKE, 0,
    43, SPECIES_MACHOKE, 0,
    38, SPECIES_MACHOKE, SPECIES_MACHOP, SPECIES_MACHOKE, 0,
    /* Victory Road 2F */
    43, SPECIES_MACHOKE, SPECIES_MACHOP, SPECIES_MACHOKE, 0,
};

/* ---- Rival1 (class 25) ------------------------------------------ */
static const uint8_t gRival1Parties[] = {
    5, SPECIES_SQUIRTLE, 0,
    5, SPECIES_BULBASAUR, 0,
    5, SPECIES_CHARMANDER, 0,
    /* Route 22 */
    TRAINER_PARTY_FMT_B, 9, SPECIES_PIDGEY, 8, SPECIES_SQUIRTLE, 0,
    TRAINER_PARTY_FMT_B, 9, SPECIES_PIDGEY, 8, SPECIES_BULBASAUR, 0,
    TRAINER_PARTY_FMT_B, 9, SPECIES_PIDGEY, 8, SPECIES_CHARMANDER, 0,
    /* Cerulean City */
    TRAINER_PARTY_FMT_B, 18, SPECIES_PIDGEOTTO, 15, SPECIES_ABRA, 15, SPECIES_RATTATA, 17,
    SPECIES_SQUIRTLE, 0,
    TRAINER_PARTY_FMT_B, 18, SPECIES_PIDGEOTTO, 15, SPECIES_ABRA, 15, SPECIES_RATTATA, 17,
    SPECIES_BULBASAUR, 0,
    TRAINER_PARTY_FMT_B, 18, SPECIES_PIDGEOTTO, 15, SPECIES_ABRA, 15, SPECIES_RATTATA, 17,
    SPECIES_CHARMANDER, 0,
};

/* ---- ProfOak (class 26) ------------------------------------------ */
static const uint8_t gProfOakParties[] = {
    /* Unused */
    TRAINER_PARTY_FMT_B, 66, SPECIES_TAUROS, 67, SPECIES_EXEGGUTOR, 68, SPECIES_ARCANINE, 69,
    SPECIES_BLASTOISE, 70, SPECIES_GYARADOS, 0,
    TRAINER_PARTY_FMT_B, 66, SPECIES_TAUROS, 67, SPECIES_EXEGGUTOR, 68, SPECIES_ARCANINE, 69,
    SPECIES_VENUSAUR, 70, SPECIES_GYARADOS, 0,
    TRAINER_PARTY_FMT_B, 66, SPECIES_TAUROS, 67, SPECIES_EXEGGUTOR, 68, SPECIES_ARCANINE, 69,
    SPECIES_CHARIZARD, 70, SPECIES_GYARADOS, 0,
};

/* ---- Chief (class 27) ------------------------------------------ */
static const uint8_t gChiefParties[] = {
    0,
};

/* ---- Scientist (class 28) ------------------------------------------ */
static const uint8_t gScientistParties[] = {
    /* Unused */
    34, SPECIES_KOFFING, SPECIES_VOLTORB, 0,
    /* Silph Co. 2F */
    26, SPECIES_GRIMER, SPECIES_WEEZING, SPECIES_KOFFING, SPECIES_WEEZING, 0,
    28, SPECIES_MAGNEMITE, SPECIES_VOLTORB, SPECIES_MAGNETON, 0,
    /* Silph Co. 3F/Mansion 1F */
    29, SPECIES_ELECTRODE, SPECIES_WEEZING, 0,
    /* Silph Co. 4F */
    33, SPECIES_ELECTRODE, 0,
    /* Silph Co. 5F */
    26, SPECIES_MAGNETON, SPECIES_KOFFING, SPECIES_WEEZING, SPECIES_MAGNEMITE, 0,
    /* Silph Co. 6F */
    25, SPECIES_VOLTORB, SPECIES_KOFFING, SPECIES_MAGNETON, SPECIES_MAGNEMITE, SPECIES_KOFFING,
    0,
    /* Silph Co. 7F */
    29, SPECIES_ELECTRODE, SPECIES_MUK, 0,
    /* Silph Co. 8F */
    29, SPECIES_GRIMER, SPECIES_ELECTRODE, 0,
    /* Silph Co. 9F */
    28, SPECIES_VOLTORB, SPECIES_KOFFING, SPECIES_MAGNETON, 0,
    /* Silph Co. 10F */
    29, SPECIES_MAGNEMITE, SPECIES_KOFFING, 0,
    /* Mansion 3F */
    33, SPECIES_MAGNEMITE, SPECIES_MAGNETON, SPECIES_VOLTORB, 0,
    /* Mansion B1F */
    34, SPECIES_MAGNEMITE, SPECIES_ELECTRODE, 0,
};

/* ---- Giovanni (class 29) ------------------------------------------ */
static const uint8_t gGiovanniParties[] = {
    /* Rocket Hideout B4F */
    TRAINER_PARTY_FMT_B, 25, SPECIES_ONIX, 24, SPECIES_RHYHORN, 29, SPECIES_KANGASKHAN, 0,
    /* Silph Co. 11F */
    TRAINER_PARTY_FMT_B, 37, SPECIES_NIDORINO, 35, SPECIES_KANGASKHAN, 37, SPECIES_RHYHORN, 41,
    SPECIES_NIDOQUEEN, 0,
    /* Viridian Gym */
    TRAINER_PARTY_FMT_B, 45, SPECIES_RHYHORN, 42, SPECIES_DUGTRIO, 44, SPECIES_NIDOQUEEN, 45,
    SPECIES_NIDOKING, 50, SPECIES_RHYDON, 0,
};

/* ---- Rocket (class 30) ------------------------------------------ */
static const uint8_t gRocketParties[] = {
    /* Mt. Moon B2F */
    13, SPECIES_RATTATA, SPECIES_ZUBAT, 0,
    11, SPECIES_SANDSHREW, SPECIES_RATTATA, SPECIES_ZUBAT, 0,
    12, SPECIES_ZUBAT, SPECIES_EKANS, 0,
    16, SPECIES_RATICATE, 0,
    /* Cerulean City */
    17, SPECIES_MACHOP, SPECIES_DROWZEE, 0,
    /* Route 24 */
    15, SPECIES_EKANS, SPECIES_ZUBAT, 0,
    /* Game Corner */
    20, SPECIES_RATICATE, SPECIES_ZUBAT, 0,
    /* Rocket Hideout B1F */
    21, SPECIES_DROWZEE, SPECIES_MACHOP, 0,
    21, SPECIES_RATICATE, SPECIES_RATICATE, 0,
    20, SPECIES_GRIMER, SPECIES_KOFFING, SPECIES_KOFFING, 0,
    19, SPECIES_RATTATA, SPECIES_RATICATE, SPECIES_RATICATE, SPECIES_RATTATA, 0,
    22, SPECIES_GRIMER, SPECIES_KOFFING, 0,
    /* Rocket Hideout B2F */
    17, SPECIES_ZUBAT, SPECIES_KOFFING, SPECIES_GRIMER, SPECIES_ZUBAT, SPECIES_RATICATE, 0,
    /* Rocket Hideout B3F */
    20, SPECIES_RATTATA, SPECIES_RATICATE, SPECIES_DROWZEE, 0,
    21, SPECIES_MACHOP, SPECIES_MACHOP, 0,
    /* Rocket Hideout B4F */
    23, SPECIES_SANDSHREW, SPECIES_EKANS, SPECIES_SANDSLASH, 0,
    23, SPECIES_EKANS, SPECIES_SANDSHREW, SPECIES_ARBOK, 0,
    21, SPECIES_KOFFING, SPECIES_ZUBAT, 0,
    /* Pokémon Tower 7F */
    25, SPECIES_ZUBAT, SPECIES_ZUBAT, SPECIES_GOLBAT, 0,
    26, SPECIES_KOFFING, SPECIES_DROWZEE, 0,
    23, SPECIES_ZUBAT, SPECIES_RATTATA, SPECIES_RATICATE, SPECIES_ZUBAT, 0,
    /* Unused */
    26, SPECIES_DROWZEE, SPECIES_KOFFING, 0,
    /* Silph Co. 2F */
    29, SPECIES_CUBONE, SPECIES_ZUBAT, 0,
    25, SPECIES_GOLBAT, SPECIES_ZUBAT, SPECIES_ZUBAT, SPECIES_RATICATE, SPECIES_ZUBAT, 0,
    /* Silph Co. 3F */
    28, SPECIES_RATICATE, SPECIES_HYPNO, SPECIES_RATICATE, 0,
    /* Silph Co. 4F */
    29, SPECIES_MACHOP, SPECIES_DROWZEE, 0,
    28, SPECIES_EKANS, SPECIES_ZUBAT, SPECIES_CUBONE, 0,
    /* Silph Co. 5F */
    33, SPECIES_ARBOK, 0,
    33, SPECIES_HYPNO, 0,
    /* Silph Co. 6F */
    29, SPECIES_MACHOP, SPECIES_MACHOKE, 0,
    28, SPECIES_ZUBAT, SPECIES_ZUBAT, SPECIES_GOLBAT, 0,
    /* Silph Co. 7F */
    26, SPECIES_RATICATE, SPECIES_ARBOK, SPECIES_KOFFING, SPECIES_GOLBAT, 0,
    29, SPECIES_CUBONE, SPECIES_CUBONE, 0,
    29, SPECIES_SANDSHREW, SPECIES_SANDSLASH, 0,
    /* Silph Co. 8F */
    26, SPECIES_RATICATE, SPECIES_ZUBAT, SPECIES_GOLBAT, SPECIES_RATTATA, 0,
    28, SPECIES_WEEZING, SPECIES_GOLBAT, SPECIES_KOFFING, 0,
    /* Silph Co. 9F */
    28, SPECIES_DROWZEE, SPECIES_GRIMER, SPECIES_MACHOP, 0,
    28, SPECIES_GOLBAT, SPECIES_DROWZEE, SPECIES_HYPNO, 0,
    /* Silph Co. 10F */
    33, SPECIES_MACHOKE, 0,
    /* Silph Co. 11F */
    25, SPECIES_RATTATA, SPECIES_RATTATA, SPECIES_ZUBAT, SPECIES_RATTATA, SPECIES_EKANS, 0,
    32, SPECIES_CUBONE, SPECIES_DROWZEE, SPECIES_MAROWAK, 0,
};

/* ---- CooltrainerM (class 31) ------------------------------------------ */
static const uint8_t gCooltrainerMParties[] = {
    /* Viridian Gym */
    39, SPECIES_NIDORINO, SPECIES_NIDOKING, 0,
    /* Victory Road 3F */
    43, SPECIES_EXEGGUTOR, SPECIES_CLOYSTER, SPECIES_ARCANINE, 0,
    43, SPECIES_KINGLER, SPECIES_TENTACRUEL, SPECIES_BLASTOISE, 0,
    /* Unused */
    45, SPECIES_KINGLER, SPECIES_STARMIE, 0,
    /* Victory Road 1F */
    42, SPECIES_IVYSAUR, SPECIES_WARTORTLE, SPECIES_CHARMELEON, SPECIES_CHARIZARD, 0,
    /* Unused */
    44, SPECIES_IVYSAUR, SPECIES_WARTORTLE, SPECIES_CHARMELEON, 0,
    49, SPECIES_NIDOKING, 0,
    44, SPECIES_KINGLER, SPECIES_CLOYSTER, 0,
    /* Viridian Gym */
    39, SPECIES_SANDSLASH, SPECIES_DUGTRIO, 0,
    43, SPECIES_RHYHORN, 0,
};

/* ---- CooltrainerF (class 32) ------------------------------------------ */
static const uint8_t gCooltrainerFParties[] = {
    /* Celadon Gym */
    24, SPECIES_WEEPINBELL, SPECIES_GLOOM, SPECIES_IVYSAUR, 0,
    /* Victory Road 3F */
    43, SPECIES_BELLSPROUT, SPECIES_WEEPINBELL, SPECIES_VICTREEBEL, 0,
    43, SPECIES_PARASECT, SPECIES_DEWGONG, SPECIES_CHANSEY, 0,
    /* Unused */
    46, SPECIES_VILEPLUME, SPECIES_BUTTERFREE, 0,
    /* Victory Road 1F */
    44, SPECIES_PERSIAN, SPECIES_NINETALES, 0,
    /* Unused */
    45, SPECIES_IVYSAUR, SPECIES_VENUSAUR, 0,
    45, SPECIES_NIDORINA, SPECIES_NIDOQUEEN, 0,
    43, SPECIES_PERSIAN, SPECIES_NINETALES, SPECIES_RAICHU, 0,
};

/* ---- Bruno (class 33) ------------------------------------------ */
static const uint8_t gBrunoParties[] = {
    TRAINER_PARTY_FMT_B, 53, SPECIES_ONIX, 55, SPECIES_HITMONCHAN, 55, SPECIES_HITMONLEE, 56,
    SPECIES_ONIX, 58, SPECIES_MACHAMP, 0,
};

/* ---- Brock (class 34) ------------------------------------------ */
static const uint8_t gBrockParties[] = {
    TRAINER_PARTY_FMT_B, 12, SPECIES_GEODUDE, 14, SPECIES_ONIX, 0,
};

/* ---- Misty (class 35) ------------------------------------------ */
static const uint8_t gMistyParties[] = {
    TRAINER_PARTY_FMT_B, 18, SPECIES_STARYU, 21, SPECIES_STARMIE, 0,
};

/* ---- LtSurge (class 36) ------------------------------------------ */
static const uint8_t gLtSurgeParties[] = {
    TRAINER_PARTY_FMT_B, 21, SPECIES_VOLTORB, 18, SPECIES_PIKACHU, 24, SPECIES_RAICHU, 0,
};

/* ---- Erika (class 37) ------------------------------------------ */
static const uint8_t gErikaParties[] = {
    TRAINER_PARTY_FMT_B, 29, SPECIES_VICTREEBEL, 24, SPECIES_TANGELA, 29, SPECIES_VILEPLUME, 0,
};

/* ---- Koga (class 38) ------------------------------------------ */
static const uint8_t gKogaParties[] = {
    TRAINER_PARTY_FMT_B, 37, SPECIES_KOFFING, 39, SPECIES_MUK, 37, SPECIES_KOFFING, 43,
    SPECIES_WEEZING, 0,
};

/* ---- Blaine (class 39) ------------------------------------------ */
static const uint8_t gBlaineParties[] = {
    TRAINER_PARTY_FMT_B, 42, SPECIES_GROWLITHE, 40, SPECIES_PONYTA, 42, SPECIES_RAPIDASH, 47,
    SPECIES_ARCANINE, 0,
};

/* ---- Sabrina (class 40) ------------------------------------------ */
static const uint8_t gSabrinaParties[] = {
    TRAINER_PARTY_FMT_B, 38, SPECIES_KADABRA, 37, SPECIES_MR_MIME, 38, SPECIES_VENOMOTH, 43,
    SPECIES_ALAKAZAM, 0,
};

/* ---- Gentleman (class 41) ------------------------------------------ */
static const uint8_t gGentlemanParties[] = {
    /* SS Anne 1F Rooms */
    18, SPECIES_GROWLITHE, SPECIES_GROWLITHE, 0,
    19, SPECIES_NIDORAN_M, SPECIES_NIDORAN_F, 0,
    /* SS Anne 2F Rooms/Vermilion Gym */
    23, SPECIES_PIKACHU, 0,
    /* Unused */
    48, SPECIES_PRIMEAPE, 0,
    /* SS Anne 2F Rooms */
    17, SPECIES_GROWLITHE, SPECIES_PONYTA, 0,
};

/* ---- Rival2 (class 42) ------------------------------------------ */
static const uint8_t gRival2Parties[] = {
    /* SS Anne 2F */
    TRAINER_PARTY_FMT_B, 19, SPECIES_PIDGEOTTO, 16, SPECIES_RATICATE, 18, SPECIES_KADABRA, 20,
    SPECIES_WARTORTLE, 0,
    TRAINER_PARTY_FMT_B, 19, SPECIES_PIDGEOTTO, 16, SPECIES_RATICATE, 18, SPECIES_KADABRA, 20,
    SPECIES_IVYSAUR, 0,
    TRAINER_PARTY_FMT_B, 19, SPECIES_PIDGEOTTO, 16, SPECIES_RATICATE, 18, SPECIES_KADABRA, 20,
    SPECIES_CHARMELEON, 0,
    /* Pokémon Tower 2F */
    TRAINER_PARTY_FMT_B, 25, SPECIES_PIDGEOTTO, 23, SPECIES_GROWLITHE, 22, SPECIES_EXEGGCUTE,
    20, SPECIES_KADABRA, 25, SPECIES_WARTORTLE, 0,
    TRAINER_PARTY_FMT_B, 25, SPECIES_PIDGEOTTO, 23, SPECIES_GYARADOS, 22, SPECIES_GROWLITHE,
    20, SPECIES_KADABRA, 25, SPECIES_IVYSAUR, 0,
    TRAINER_PARTY_FMT_B, 25, SPECIES_PIDGEOTTO, 23, SPECIES_EXEGGCUTE, 22, SPECIES_GYARADOS,
    20, SPECIES_KADABRA, 25, SPECIES_CHARMELEON, 0,
    /* Silph Co. 7F */
    TRAINER_PARTY_FMT_B, 37, SPECIES_PIDGEOT, 38, SPECIES_GROWLITHE, 35, SPECIES_EXEGGCUTE, 35,
    SPECIES_ALAKAZAM, 40, SPECIES_BLASTOISE, 0,
    TRAINER_PARTY_FMT_B, 37, SPECIES_PIDGEOT, 38, SPECIES_GYARADOS, 35, SPECIES_GROWLITHE, 35,
    SPECIES_ALAKAZAM, 40, SPECIES_VENUSAUR, 0,
    TRAINER_PARTY_FMT_B, 37, SPECIES_PIDGEOT, 38, SPECIES_EXEGGCUTE, 35, SPECIES_GYARADOS, 35,
    SPECIES_ALAKAZAM, 40, SPECIES_CHARIZARD, 0,
    /* Route 22 */
    TRAINER_PARTY_FMT_B, 47, SPECIES_PIDGEOT, 45, SPECIES_RHYHORN, 45, SPECIES_GROWLITHE, 47,
    SPECIES_EXEGGCUTE, 50, SPECIES_ALAKAZAM, 53, SPECIES_BLASTOISE, 0,
    TRAINER_PARTY_FMT_B, 47, SPECIES_PIDGEOT, 45, SPECIES_RHYHORN, 45, SPECIES_GYARADOS, 47,
    SPECIES_GROWLITHE, 50, SPECIES_ALAKAZAM, 53, SPECIES_VENUSAUR, 0,
    TRAINER_PARTY_FMT_B, 47, SPECIES_PIDGEOT, 45, SPECIES_RHYHORN, 45, SPECIES_EXEGGCUTE, 47,
    SPECIES_GYARADOS, 50, SPECIES_ALAKAZAM, 53, SPECIES_CHARIZARD, 0,
};

/* ---- Rival3 (class 43) ------------------------------------------ */
static const uint8_t gRival3Parties[] = {
    TRAINER_PARTY_FMT_B, 61, SPECIES_PIDGEOT, 59, SPECIES_ALAKAZAM, 61, SPECIES_RHYDON, 61,
    SPECIES_ARCANINE, 63, SPECIES_EXEGGUTOR, 65, SPECIES_BLASTOISE, 0,
    TRAINER_PARTY_FMT_B, 61, SPECIES_PIDGEOT, 59, SPECIES_ALAKAZAM, 61, SPECIES_RHYDON, 61,
    SPECIES_GYARADOS, 63, SPECIES_ARCANINE, 65, SPECIES_VENUSAUR, 0,
    TRAINER_PARTY_FMT_B, 61, SPECIES_PIDGEOT, 59, SPECIES_ALAKAZAM, 61, SPECIES_RHYDON, 61,
    SPECIES_EXEGGUTOR, 63, SPECIES_GYARADOS, 65, SPECIES_CHARIZARD, 0,
};

/* ---- Lorelei (class 44) ------------------------------------------ */
static const uint8_t gLoreleiParties[] = {
    TRAINER_PARTY_FMT_B, 54, SPECIES_DEWGONG, 53, SPECIES_CLOYSTER, 54, SPECIES_SLOWBRO, 56,
    SPECIES_JYNX, 56, SPECIES_LAPRAS, 0,
};

/* ---- Channeler (class 45) ------------------------------------------ */
static const uint8_t gChannelerParties[] = {
    /* Unused */
    22, SPECIES_GASTLY, 0,
    24, SPECIES_GASTLY, 0,
    23, SPECIES_GASTLY, SPECIES_GASTLY, 0,
    24, SPECIES_GASTLY, 0,
    /* Pokémon Tower 3F */
    23, SPECIES_GASTLY, 0,
    24, SPECIES_GASTLY, 0,
    /* Unused */
    24, SPECIES_HAUNTER, 0,
    /* Pokémon Tower 3F */
    22, SPECIES_GASTLY, 0,
    /* Pokémon Tower 4F */
    24, SPECIES_GASTLY, 0,
    23, SPECIES_GASTLY, SPECIES_GASTLY, 0,
    /* Unused */
    24, SPECIES_GASTLY, 0,
    /* Pokémon Tower 4F */
    22, SPECIES_GASTLY, 0,
    /* Unused */
    24, SPECIES_GASTLY, 0,
    /* Pokémon Tower 5F */
    23, SPECIES_HAUNTER, 0,
    /* Unused */
    24, SPECIES_GASTLY, 0,
    /* Pokémon Tower 5F */
    22, SPECIES_GASTLY, 0,
    24, SPECIES_GASTLY, 0,
    22, SPECIES_HAUNTER, 0,
    /* Pokémon Tower 6F */
    22, SPECIES_GASTLY, SPECIES_GASTLY, SPECIES_GASTLY, 0,
    24, SPECIES_GASTLY, 0,
    24, SPECIES_GASTLY, 0,
    /* Saffron Gym */
    34, SPECIES_GASTLY, SPECIES_HAUNTER, 0,
    38, SPECIES_HAUNTER, 0,
    33, SPECIES_GASTLY, SPECIES_GASTLY, SPECIES_HAUNTER, 0,
};

/* ---- Agatha (class 46) ------------------------------------------ */
static const uint8_t gAgathaParties[] = {
    TRAINER_PARTY_FMT_B, 56, SPECIES_GENGAR, 56, SPECIES_GOLBAT, 55, SPECIES_HAUNTER, 58,
    SPECIES_ARBOK, 60, SPECIES_GENGAR, 0,
};

/* ---- Lance (class 47) ------------------------------------------ */
static const uint8_t gLanceParties[] = {
    TRAINER_PARTY_FMT_B, 58, SPECIES_GYARADOS, 56, SPECIES_DRAGONAIR, 56, SPECIES_DRAGONAIR,
    60, SPECIES_AERODACTYL, 62, SPECIES_DRAGONITE, 0,
};

const uint8_t * const gTrainerPartyData[NUM_TRAINERS] = {
    gYoungsterParties, /* class 1 */
    gBugCatcherParties, /* class 2 */
    gLassParties, /* class 3 */
    gSailorParties, /* class 4 */
    gJrTrainerMParties, /* class 5 */
    gJrTrainerFParties, /* class 6 */
    gPokemaniacParties, /* class 7 */
    gSuperNerdParties, /* class 8 */
    gHikerParties, /* class 9 */
    gBikerParties, /* class 10 */
    gBurglarParties, /* class 11 */
    gEngineerParties, /* class 12 */
    gUnusedJugglerParties, /* class 13 */
    gFisherParties, /* class 14 */
    gSwimmerParties, /* class 15 */
    gCueBallParties, /* class 16 */
    gGamblerParties, /* class 17 */
    gBeautyParties, /* class 18 */
    gPsychicParties, /* class 19 */
    gRockerParties, /* class 20 */
    gJugglerParties, /* class 21 */
    gTamerParties, /* class 22 */
    gBirdKeeperParties, /* class 23 */
    gBlackbeltParties, /* class 24 */
    gRival1Parties, /* class 25 */
    gProfOakParties, /* class 26 */
    gChiefParties, /* class 27 */
    gScientistParties, /* class 28 */
    gGiovanniParties, /* class 29 */
    gRocketParties, /* class 30 */
    gCooltrainerMParties, /* class 31 */
    gCooltrainerFParties, /* class 32 */
    gBrunoParties, /* class 33 */
    gBrockParties, /* class 34 */
    gMistyParties, /* class 35 */
    gLtSurgeParties, /* class 36 */
    gErikaParties, /* class 37 */
    gKogaParties, /* class 38 */
    gBlaineParties, /* class 39 */
    gSabrinaParties, /* class 40 */
    gGentlemanParties, /* class 41 */
    gRival2Parties, /* class 42 */
    gRival3Parties, /* class 43 */
    gLoreleiParties, /* class 44 */
    gChannelerParties, /* class 45 */
    gAgathaParties, /* class 46 */
    gLanceParties, /* class 47 */
};

const uint16_t gTrainerBaseMoney[NUM_TRAINERS] = {
    1500, /* class 1 */
    1000, /* class 2 */
    1500, /* class 3 */
    3000, /* class 4 */
    2000, /* class 5 */
    2000, /* class 6 */
    5000, /* class 7 */
    2500, /* class 8 */
    3500, /* class 9 */
    2000, /* class 10 */
    9000, /* class 11 */
    5000, /* class 12 */
    3500, /* class 13 */
    3500, /* class 14 */
    500, /* class 15 */
    2500, /* class 16 */
    7000, /* class 17 */
    7000, /* class 18 */
    1000, /* class 19 */
    2500, /* class 20 */
    3500, /* class 21 */
    4000, /* class 22 */
    2500, /* class 23 */
    2500, /* class 24 */
    3500, /* class 25 */
    9900, /* class 26 */
    3000, /* class 27 */
    5000, /* class 28 */
    9900, /* class 29 */
    3000, /* class 30 */
    3500, /* class 31 */
    3500, /* class 32 */
    9900, /* class 33 */
    9900, /* class 34 */
    9900, /* class 35 */
    9900, /* class 36 */
    9900, /* class 37 */
    9900, /* class 38 */
    9900, /* class 39 */
    9900, /* class 40 */
    7000, /* class 41 */
    6500, /* class 42 */
    9900, /* class 43 */
    9900, /* class 44 */
    3000, /* class 45 */
    9900, /* class 46 */
    9900, /* class 47 */
};
