#pragma once
/* trainer_sprites.h -- Trainer battle sprite tile data.
 * Auto-generated by tools/extract_trainer_sprites.py
 * 47 trainer classes, each 49 tiles x 16 bytes = 784 bytes.
 * Index: [trainer_class - 1]  (trainer_class is 1-based)
 * ALWAYS refer to pokered-master data/trainers/pic_pointers_money.asm. */
#include <stdint.h>
#include "game/constants.h"       /* NUM_TRAINERS = 47 */
#define TRAINER_CANVAS_TILES 49   /* 7x7 tile canvas, same as pokemon front sprites */
extern const uint8_t gTrainerFrontSprite[NUM_TRAINERS][TRAINER_CANVAS_TILES][16];
extern const char * const gTrainerClassNames[NUM_TRAINERS];
